### ISSUE TITLE
Where is the exe file

### ISSUE THREAD

**Issue by ZPH666666** [ImAiiR/QobuzDownloaderX#1]
Where is the exe file,I don't know how to use it

**Comment by ImAiiR** [comment]
1. Go to the releases - https://github.com/ImAiiR/QobuzDownloaderX/releases
2. Download the latest .zip file (Which as of typing this, is "QBDLX_0.9.8.7.zip")
3. Extract both the .exe and .dll into a new directory (or any directory, doesn't matter as long as they are together)
4. Run the .exe and log in. You will need to get an app_id from Qobuz. I can't describe how to get it, but if you watch the traffic while using the Qobuz Web Player, you can find it that way.
