### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by balleno75** [ImAiiR/QobuzDownloaderX#10]
Hello, in version 0.9.9.10, any download fails,

https://open.qobuz.com/album/zws6itr39mxqb

![image](https://user-images.githubusercontent.com/39314271/77558531-5576a500-6ebb-11ea-8778-4f5838936430.png)

This error occurs since version 0.9.9.10. So far, I have been able to download without problems.

Please can you check it? Thank you. Greetings.

**Comment by balleno75** [comment]
I have discovered the problem,

Apparently now, it depends on the language of the S.O. Windows, since I have tested it on an S.O. with language in English (USA) and has been downloaded without problems.

![image](https://user-images.githubusercontent.com/39314271/77561850-8bb62380-6ebf-11ea-9eaa-d683be256ec6.png)

**Comment by devandikurniarestuandika** [comment]
yes, same problem. should i change my PC language to English?
but, i got other problem.

System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment]
I'm starting to wonder 2 things. 1, are people getting different types of responses from the API for the release date value? 2, is it all the same and I should worry about changing how I'm converting it so the `DateTime` error stops happening?

I've had someone get the download to work on 0.9.9.9 and the release date was working, which is what makes me wonder if the API is giving different results depending on the person.



> yes, same problem. should i change my PC language to English?
> but, i got other problem.
> 
> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
> at System.Net.HttpWebRequest.GetResponse()
> at QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)

For this one, is it while logging in? or is it when trying to download? If while logging in that's still being looked in to. For some login is working fine, and for others it isn't, and I haven't been able to find a reason behind it yet.

**Comment by devandikurniarestuandika** [comment]
when I try to download a track, and it happens not responding

**Comment by balleno75** [comment]
The language of my region is Spanish (Spain), and when changing it to English (USA), the download has worked correctly, so it fixes the error.

This problem has been introduced since version 0.9.9.10.

I have seen the program code and the changes applied in version 0.9.9.10 and the error may come, for this conversion,

QobuzDownloaderX/Form1.cs 

        // Set DateTime for new date formatting.
        System.DateTime dateTime = new System.DateTime(1970, 1, 1, 0, 0, 0, 0);

        public string DateConvertion(string Input)
        {
            var date = DateTime.ParseExact(Input, "M/d/yyyy hh:mm:ss tt",
                                            CultureInfo.InvariantCulture);

            return date.ToString("yyyy-MM-dd");
        }

**Comment by balleno75** [comment]
in Spain the date format is d/M/yyyy and for this reason it generates the error

**Comment by ImAiiR** [comment]
So it seems Qobuz added the original way they showed release dates back, so the 0.9.9.10 update wasn't even needed. I've reverted the code back to how it was, 0.9.9.9 should work for you until the next update, since there wasn't any other features added in 0.9.9.10.

I'll be trying to get the next update out ASAP so the update box will stop being an annoyance for those stuck on 0.9.9.9.

**Comment by balleno75** [comment]
thank you. Greetings

**Comment by ImAiiR** [comment]
Alright, all should be fixed for the release date bug in version 0.9.9.11. If you run into anything else directly related to the release date, I'll re-open this.

https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.11
