### ISSUE TITLE
No longer able to find albums using artist link. 

### ISSUE THREAD

**Issue by Wim1975** [ImAiiR/QobuzDownloaderX#100]
Hi the app is no longer able grabbing the album ids from an artist.

example
https://open.qobuz.com/artist/1843607
shows "grabbing ids" and then the app seems to hang as nothing happens.

Individual downloads of albums however still seems to work.

I hope this must be something minor, and easy to fix.

**Comment by Wim1975** [comment]
Sometimes this error pops up when trying to download an artist

https://open.qobuz.com/artist/624049

**ERROR: 404
Error message is "No result matching given argument"
This usually means the link is invalid, or isn't available in the region your account is from.**

When I copy the link to the browser, the link is working.
The album pictures are loading much faster than before, so I assume Qobuz made some changes,
causing the artist download no longer to work.

**Comment by ThePlayingGoblin** [comment]
I'm having this same problem too.

**Comment by Wim1975** [comment]
Hello, Is this app still being updated ?
Would be nice since it is quite a huge problem not being able to download multiple albums at once !

**Comment by ThePlayingGoblin** [comment]
I tried contacting him and he never responded. Right now I can only grab labels and single albums.
