### ISSUE TITLE
stop working since today ?

### ISSUE THREAD

**Issue by Fraizer2600** [ImAiiR/QobuzDownloaderX#101]
Hello

i can listen music on qobuz by navigator or app but nothing happen with the QobuzDownloaderX... i can login and is like it try to DL the 1st sound but nothing happen.

i tryed with many different = same result. 2 days ago all was working perfectly

i tryed on another computer = same problem

maybe QobuzDownloaderX need to be updated ?  or this is the end ?

thank you all

**Comment by Fraizer2600** [comment]
i just try with Allavasoft and all working well

**Comment by Wim1975** [comment]
I can no longer download using artist links but it still works when you download the album links seperately.
Which is of course a huge job if you'd like the full collection of a certain artist :-(
(I posted this in #100). I guess Qobuz changed their formatting and the QobuzDownloader's parsing needs to be adjusted.

Did you try to download a seperate album and does this still work for you?
