### ISSUE TITLE
AVG and Microsoft defender don't like this?

### ISSUE THREAD

**Issue by paddyb2** [ImAiiR/QobuzDownloaderX#106]
I had this working last week, but just tried it again from the exe file and AVG moved it to virus vault. I tried installing again and Microsoft Defender stopped it from running. 

Is there any Malware included in the exe?

**Comment by KENESOLJASMUSIC** [comment]
Of course not. The best antivirus sits at the computer. I recommend uninstalling AVG and never remembering about it.
