### ISSUE TITLE
Help me download these songs!

### ISSUE THREAD

**Issue by KENESOLJASMUSIC** [ImAiiR/QobuzDownloaderX#107]
Please help me download these songs! Unfortunately, they are not available in my country.
https://play.qobuz.com/album/0060252740531
https://open.qobuz.com/track/40236813
https://open.qobuz.com/track/54838986
https://open.qobuz.com/track/29719593
https://open.qobuz.com/track/92800440
https://open.qobuz.com/track/92800441
https://open.qobuz.com/track/85104570
https://open.qobuz.com/track/13910846
https://open.qobuz.com/track/62739322

**Comment by KENESOLJASMUSIC** [comment]
musicboxwninehundred@gmail.com

**Comment by EinUser2** [comment]
What do I get for this?

**Comment by KENESOLJASMUSIC** [comment]
Many thanks! I don't even know what to suggest.
