### ISSUE TITLE
 QobuzDownloaderX for macOS

### ISSUE THREAD

**Issue by ThePlayingGoblin** [ImAiiR/QobuzDownloaderX#109]
hello. Is there any way to port qobuzdownloaderX to macos? Whether if it's recompiling the code, or making another version of this program for macos?

**Comment by neaumusic** [comment]
works for me, `brew install --cask whisky` then launch Whisky.app, create a bottle, extract the release zip to the C: drive in that bottle, Winetricks.. → DLLs → `dotnet46` and just install all the stuff that pops up. then just run the .exe in your C drive and it should work. I also installed corefonts and vcrun2022 but dont think those were required
