### ISSUE TITLE
No longer able to downoad entire artists

### ISSUE THREAD

**Issue by sramsay100** [ImAiiR/QobuzDownloaderX#112]
No longer able to downoad entire artists from any artist link:

example: https://open.qobuz.com/artist/######

Also tried https://play.qobuz.com/artist/###### but no joy.

It gets stuck on: Grabbing Albums IDs

As I am sure as everyone is aware this used to grab a list of Album IDs and then download then all in one operation.

Can someone else confirm that they too are expereincing the same issue please? Many thanks in advance.

**Comment by schroederrt** [comment]
I just tried this and it worked for me.  

Honestly didn't know this worked

**Comment by DrSKiZZ** [comment]
It's working for me but the album titles now have the Album IDs in the title now versus downloading them 1 by 1.

**Comment by sramsay100** [comment]
@

> It's working for me but the album titles now have the Album IDs in the title now versus downloading them 1 by 1.

Hi

**Comment by sramsay100** [comment]
Hi @DrSKiZZ 

The Album IDs are intentional, without them you would have a lot of overwritten audio tracks where albums names are the same where different album versions exist.

There are two other projects, similar to this one that have this issue because they do not include a unique key in their folder structure writing.

Thanks for your feedback informing me that it is working for you. Very handy to know.

Hi @schroederrt 

Thanks for your response and feedback on this issue, maybe it is my particular machine then. I am currently creating a clean WIn10 image on a new machine. I will install the app this afternoon and test again. If all is okay, I will then close this issue. Thanks.

**Comment by sramsay100** [comment]
Thanks for all your help. This feature is now working on a fresh install of Win10 so this must have been a unique issue. This issue will now e closed.
