### ISSUE TITLE
Downloader freezes

### ISSUE THREAD

**Issue by Mascotra** [ImAiiR/QobuzDownloaderX#113]
Program freezes when I open search

**Comment by huzld** [comment]
Having the same problem.

**Comment by TheBossi** [comment]
I have the same issue too

**Comment by sramsay100** [comment]
My seacrh function on my installation on Windows 10 works fine. So, I guess this may confirm this to be a Win11 issue.

Workaround for now:
I never use this function myself. I always have Qobuz App or Qobuz WebPlayer loaded, find what i need, use the three dots menu, select Share and click to copy the link. Then simply paste this into QobuzDownloaderX.

Hope this helps.
