### ISSUE TITLE
Couldn't obtain app info

### ISSUE THREAD

**Issue by TheM14** [ImAiiR/QobuzDownloaderX#116]
Until yesterday, it works when I was login. But now I can't login and it shows "couldn't obtain app info".

**Comment by lx30011** [comment]
Same here

**Comment by schroederrt** [comment]
I got the same.  It seems that Qobuz may have made a change in the bundle.js which is used to determine the app secret and login.  

I was able to review and identify that there was an issue identifying the initial seed.

If you can open your LoginForm-v2.cs file and change line 401 from this:

var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\\):f.initialSeed\\(\"(?<seed>.*?)\",window.utimezone.berlin\\)").Groups;
                var bundleSeed = bundleLog2[1].Value;

to this:

var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\\):d.initialSeed\\(\"(?<seed>.*?)\",window.utimezone.berlin\\)").Groups;
                var bundleSeed = bundleLog2[1].Value;

it should work again.

**Comment by HotdogNoire** [comment]
> 

This does work!

**Comment by DanDare67** [comment]
I wish I knew how to rebuild. I will have to wait for a new release.

Thanks all for giving me hope it is fixable.

**Comment by schroederrt** [comment]
> I wish I knew how to rebuild. I will have to wait for a new release.
> 
> Thanks all for giving me hope it is fixable.

Don't you have to build this first to use it at all?  I've not found a release with the executable, I've always had to build it.

**Comment by DanDare67** [comment]
> Don't you have to build this first to use it at all? I've not found a release with the executable, I've always had to build it.

On the **Code** page under [Releases](https://github.com/ImAiiR/QobuzDownloaderX/releases) the zip file contains a EXE.

Would love to learn how to compile (right word?), but that is outside of my area of expertise. Seems like a useful skill, just never had the opportunity to learn it.

**Comment by ImAiiR** [comment]
I've been rewriting the program, I'll try to get it out soon. Fixes a lot of issues people have been having, just really haven't had much free time.

**Comment by LuongThang007** [comment]
> I got the same. It seems that Qobuz may have made a change in the bundle.js which is used to determine the app secret and login.
> 
> I was able to review and identify that there was an issue identifying the initial seed.
> 
> If you can open your LoginForm-v2.cs file and change line 401 from this:
> 
> var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\):f.initialSeed\("(?.*?)",window.utimezone.berlin\)").Groups; var bundleSeed = bundleLog2[1].Value;
> 
> to this:
> 
> var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\):d.initialSeed\("(?.*?)",window.utimezone.berlin\)").Groups; var bundleSeed = bundleLog2[1].Value;
> 
> it should work again after a rebuild.


Where can I find LoginForm-v2.cs file ?

**Comment by linkthehylian** [comment]
Here's the rebuild until the new release is out.
[QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)

**Comment by LuongThang007** [comment]
It worked! Thanks a lot!!

Vào Th 5, 19 thg 5, 2022 vào lúc 18:38 Andrew ***@***.***>
đã viết:

**Comment by AntonioX22** [comment]
> Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> 
> Works again just like before. 😄 

Thank you! I am now getting a new error message, I'm afraid: Login Failed

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()

**Comment by schroederrt** [comment]
> > Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> > Works again just like before. 😄
> 
> Thank you! I am now getting a new error message, I'm afraid: Login Failed
> 
> System.NullReferenceException: Object reference not set to an instance of an object. at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()

I think you may have the alternate login method selected.  Try clicking the 'Login Normally?" text under the login button and then try to login again.

**Comment by AntonioX22** [comment]
> > > Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> > > Works again just like before. 😄
> > 
> > 
> > Thank you! I am now getting a new error message, I'm afraid: Login Failed
> > System.NullReferenceException: Object reference not set to an instance of an object. at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()
> 
> I think you may have the alternate login method selected. Try clicking the 'Login Normally?" text under the login button and then try to login again.

Thank you very much, it is working now! :)

**Comment by linkthehylian** [comment]
> Thank you! I am now getting a new error message, I'm afraid: Login Failed

System.NullReferenceException: Object reference not set to an instance of an object.
at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()

Interesting, I was under the impression that the edited code would also fix the alternative way of logging in? I guess not.

It'll probably be fixed in the new release. Just login normally.

**Comment by schroederrt** [comment]
> Interesting, I was under the impression that the edited code would also fix the alternative way of logging in? I guess not.
> 
> It'll probably be fixed in the new release. Just login normally.

I noticed that issue after I figured out the fix for the regular login (accidentally left the alternate logon mode on too)....but never investigated that one since I was able to login, and I've never used the alternate logon so no idea if it worked before or not.  

I'm not the developer on this project...just trying to share what solved it for me as I poked around a bit until a new release can be made.

**Comment by masontmorris** [comment]
> Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> 
> Works again just like before. 😄 ![img](https://camo.githubusercontent.com/bac2b090181634fa2503ddf74c9eefcd3aad946f4e61e00a0ca3c60b0e736723/68747470733a2f2f692e696d6775722e636f6d2f6271716f7679672e706e67)

This works perfectly for me, thank you so much!

**Comment by q1554788327** [comment]
> Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> 
> Works again just like before. 😄 ![img](https://camo.githubusercontent.com/bac2b090181634fa2503ddf74c9eefcd3aad946f4e61e00a0ca3c60b0e736723/68747470733a2f2f692e696d6775722e636f6d2f6271716f7679672e706e67)

It does works!!Thank you.

**Comment by jwiggins1229** [comment]
I seriously had a mini panic attack, thanks for the quick patch!!

**Comment by SerCub64** [comment]
У меня  приложения не запускается а в место пароля выдаёт длинную строку. 
![Скриншот 23-05-2022 102305](https://user-images.githubusercontent.com/50100333/169764783-50eadea5-539e-44cc-9458-eca500c461b6.jpg)

**Comment by SerCub64** [comment]
![Скриншот 23-05-2022 112112](https://user-images.githubusercontent.com/50100333/169769490-f166bcde-da42-4f91-8843-929ee89b6c8e.jpg)

**Comment by Mikepshaz** [comment]
> Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> 
> Works again just like before. 😄 ![img](https://camo.githubusercontent.com/bac2b090181634fa2503ddf74c9eefcd3aad946f4e61e00a0ca3c60b0e736723/68747470733a2f2f692e696d6775722e636f6d2f6271716f7679672e706e67)

Hello,
Started facing login issues with the original exe (0.9.9.23) and got the following error in the log file. Tried login normally and with token ID.

System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

Got the exe with the rebuild edits (#116), login proceeds with a brief message " App ID & secret Obtained" but then displays failed login with the following error in the log file:
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

**Comment by neilwilkes** [comment]
> Here's the rebuild with the edits made from [#116 (comment)](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) until the new release is out. [QobuzDownloaderX.zip](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip)
> 
> Works again just like before. smile ![img](https://camo.githubusercontent.com/bac2b090181634fa2503ddf74c9eefcd3aad946f4e61e00a0ca3c60b0e736723/68747470733a2f2f692e696d6775722e636f6d2f6271716f7679672e706e67)

Many, Many thanks for the fixed build - it is indeed now working as it used to, ie flawlessly

**Comment by RogDenBoop** [comment]
Again, many thanks for a working build! Cheers!!

**Comment by Richard8969** [comment]
Since yesterday, the latest release on 20th May cannot login. Can someone help to solve the new problem? Errorlog as below:
System.NullReferenceException: Object reference not set to an instance of an object
   at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

**Comment by linkthehylian** [comment]
To anyone else still having trouble logging in with the fixed build I provided, make sure you are **logging in normally*. This means entering your email and password.

If you're still having issues when attempting to login normally, I'll try and see if I can fix the alternate login method. But I can't promise anything. Hopefully the main dev will have a new version out soon.

**Comment by eozen81** [comment]
> To anyone else still having trouble logging in with the fixed build I provided, make sure you are **logging in normally**. This means entering your email and password.
> 
> If you're still having issues when attempting to login normally, I'll try and see if I can fix the alternate login method. But I can't promise anything. Hopefully the main dev will have a new version out soon.

Unfortunately I have the login issue even though I try with my "user and password" 

![2022-09-22 12_17_58-Window](https://user-images.githubusercontent.com/36567830/191709071-7c369067-84c4-4b51-a928-3c36a41bd8b6.jpg)

**Comment by linkthehylian** [comment]
Do you think you could attach the error log? It would help a bunch. @eozen81

**Comment by linkthehylian** [comment]
@eozen81 Looked more into the issue you're having, it looks like that error message is thrown if obtaining the `bundle.js` failed according to the code. Not really sure how that's even happening.

Can you ensure that you're able to connect to https://play.qobuz.com just fine? If so, if you have any sort of VPN, try it and see if anything changes.

**Comment by eozen81** [comment]
> @eozen81 Looked more into the issue you're having, it looks like that error message is thrown if obtaining the `bundle.js` failed according to the code. Not really sure how that's even happening.
> 
> Can you ensure that you're able to connect to https://play.qobuz.com just fine and that you're logged in as well? Since that's where it's grabbing the data from.
> 
> If so, if you have any sort of VPN, try it and see if anything changes.

Thank you for your reply. But I can play without any problem on https://play.qobuz.com/ whereas I keep getting the error from QobuzDownloaderX. Yet, I installed a VPN just to understand if the problem might be related with VPN, but no, I connected VPN to a different country, checked if I can connect to https://play.qobuz.com and I could then I tried QobuzDownloaderX but the same login issue occurs.  Below are the logs:

`System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)`

**Comment by linkthehylian** [comment]
> Below are the logs:

Thank you!

> But I can play without any problem on https://play.qobuz.com/ whereas I keep getting the error from QobuzDownloaderX. Yet, I installed a VPN just to understand if the problem might be related with VPN, but no, I connected VPN to a different country, checked if I can connect to https://play.qobuz.com/ and I could then I tried QobuzDownloaderX but the same login issue occurs.

Noted. Have you tried re-entering your credentials since you've been getting that error? I noticed that the app converts passwords into Base64 according to the log you've provided. Let me know if anything changes.

**Comment by eozen81** [comment]
> > Below are the logs:
> 
> Thank you!
> 
> > But I can play without any problem on https://play.qobuz.com/ whereas I keep getting the error from QobuzDownloaderX. Yet, I installed a VPN just to understand if the problem might be related with VPN, but no, I connected VPN to a different country, checked if I can connect to https://play.qobuz.com/ and I could then I tried QobuzDownloaderX but the same login issue occurs.
> 
> Noted. Have you tried re-entering your credentials since you've been getting that error? I noticed that the app converts passwords into Base64 (which is normal behavior, I'm still able to login) according to the log you've provided. Let me know if anything changes.

I always type my user ID and password manually everytime I try, but unfortunately, it does NOT work. I also tried token log in by following up here: https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way) but the same, It did NOT work either.

**Comment by linkthehylian** [comment]
Interesting. I'm gonna be honest, but I'm not really sure where the problem lies here since it's not my app lol. 

Hey dude @ImAiiR, I know you've been busy but it's been four months since you were last active and you have a lot of users here with active Qobuz subscriptions relying on your app. Most of who aren't able to login either. 

Not trying to rush you as I'm a busy guy myself, but if you could get out that new version soon. We'd appreciate that a lot, myself included.

**Comment by Honkarar** [comment]
Thanks, I gradually put this program on hold a few months ago because I couldn't log in, then I grabbed it with allvosoft, but recently I found out that it can only grab 30 second clips, so I came here to see if it has been fixed problem. This software does work after modification. thanks very much.

**Comment by Tecko71** [comment]
This fix works for me too

**Comment by Rochambeaux** [comment]
Setup a new laptop last night and this process worked.  Came back to my desktop and tried, no joy.

This error message:

System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by jimlee2002** [comment]
> I got the same. It seems that Qobuz may have made a change in the bundle.js which is used to determine the app secret and login.
> 
> I was able to review and identify that there was an issue identifying the initial seed.
> 
> If you can open your LoginForm-v2.cs file and change line 401 from this:
> 
> var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\):f.initialSeed\("(?.*?)",window.utimezone.berlin\)").Groups; var bundleSeed = bundleLog2[1].Value;
> 
> to this:
> 
> var bundleLog2 = Regex.Match(getBundleRequest, "window.utimezone.algier\):d.initialSeed\("(?.*?)",window.utimezone.berlin\)").Groups; var bundleSeed = bundleLog2[1].Value;
> 
> it should work again after a rebuild.

For anyone who want to apply this patched yourself. I make a fork that allow easy build of executables using Github Actions. 

There is also patched program provided, which is build from my action run.

[jimlee2002/QobuzDownloaderX](https://github.com/jimlee2002/QobuzDownloaderX)

**Comment by linkthehylian** [comment]
@jimlee2002 Great work! Hopefully your patched version fixes the login issue that users were having with my rebuild I provided a couple months back.

Thank you!

**Comment by roiosdonos** [comment]
It doesn't work for me...
I have following error now:

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext() in D:\a\QobuzDownloaderX\QobuzDownloaderX\QobuzDownloaderX\LoginForm-v2.cs:line 469

What should I do?

Thanks!
