### ISSUE TITLE
Canno't login

### ISSUE THREAD

**Issue by marcusmuller** [ImAiiR/QobuzDownloaderX#117]
System.FormatException: Comprimento inválido para uma matriz ou uma cadeia de caracteres de Base 64.
   em System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   em System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   em System.Convert.FromBase64String(String s)
   em QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by DrSKiZZ** [comment]
There is a solution in issue #116 until developer updates code.
