### ISSUE TITLE
Seems that quality selection is not working, tags selection is not working.

### ISSUE THREAD

**Issue by harkis123** [ImAiiR/QobuzDownloaderX#12]
Seems that the option to select desired quality is not working, it will download all the albums that are 16bit explicit/16bit non explicit/24 bit explicit/24 bit non explicit: 
Solution: To select if you want Explicit/Non-Explicit files to download and fix the selected quality Min/Max value: 
Quality Selection: https://prnt.sc/slkow8, still downloading 16/24 bit files: https://prnt.sc/slkqns

Selection of tags is not working, ISRC/UPC number of Qobuz is still displayed on folders when downloading files
Solution: Let manually make a tag option, or just fix the issue:
Tags selected: https://prnt.sc/slksnb, showing when downloading: https://prnt.sc/slkswt

**Comment by ImAiiR** [comment]
For the first issue, Selecting the highest quality option (FLAC 24/192) will automatically download the highest quality available through Qobuz streams. For example, if an album is available in 24/44.1, and you're quality selection is 24/192, it'll still only download 24/44.1. As for downloading the explicit / non-explicit versions, you just have to find the link for the specific version you want.

For the second issue, It's not the ISRC/UPC that is displayed in the folder names, it's the Qobuz album ID, which sometimes is the UPC. This is only done when downloading from Favorites, Artists, or Labels, and it's only done to avoid having 2 folders with the exact same name, in which previously downloaded files could be overwritten without you knowing, or the program would mistake previously downloaded files for what you're currently trying to download, in which it would just skip downloading the files.
