### ISSUE TITLE
QBDLX Cant log in

### ISSUE THREAD

**Issue by brido154** [ImAiiR/QobuzDownloaderX#120]
Hi my QBDFXwas working perfectly until a few days ago. I read through some of the posts and have updated qbdlx to latest version 0.9.9.23.

I have attempted to log in with email and password and tried the Alternative method to no avail.

I love this little program, is there any experts out there who can help me please,

Error code generated as shown below

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

Thank you

Brian

**Comment by Osiris0421** [comment]
https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip

**Comment by plamberti** [comment]
@Osiris0421   thank you for your binaries.

I have a login issue with v. 0.9.9.23 (redownloaded and recompiled with VS2019 to be sure), showed up this evening.
>   My Latest_Error.log
System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e) in F:\SwDevVS19\QobuzDownloaderX-master\QobuzDownloaderX\LoginForm-v2.cs:line 412
>
My issue isn't the same ad @brido154 , but **your binaries worked**.
The question now is: how can I recompile QBDLX to get it working? I used the github .sln without changes.

Regards

**Comment by Atreyuelguerrero** [comment]
Hola
Yo tenía el mismo problema de inicio de sesión, pero me descargué este zip
[](https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip) y he podido entrar sin problemas.
Aparentemente, puede parecer la misma versión 0.9.9.23 pero no lo es, imagino que estará parcheada, yo con esta versión no he tenido que hacer el inicio alternativo. Quizás deberiais borrar las versiones anteriores y dejar solamente esta parcheada. Espero haber ayudado. Saludos

**Comment by brido154** [comment]
Hi

Thank you so much for sending the file,  alas my low in details are not accepted.I note there is no installer, I ghave always just run this program, browsing to download folder, then double clicking the exe file , this is so frustrating, any other suggestions anyone

Brian

**Comment by brido154** [comment]
HI

After unzipping I just open the QobusDownloader folder and as you say I just double click the QobuzDownloader exe file.I have this file. I don't see a setup installer so I just run the exe file


thank you

**Comment by Atreyuelguerrero** [comment]
Un archivo ejecutable, no se instala, es como un Programa portable, simplemente ejecutas el exe y funciona sin necesidad de ser instalado.

**Comment by brido154** [comment]
The annoying this this was working fine for the last 6 months. I have even from bios. Set up a clean unused windows. On an old laptop. Again tried the exe file no joy. It must be from the Qobuz side. I even tried turning all firewall off to try this. I hope the developer’s bring a new version out, I miss this so much was using daily

Thank you for your help

Regards 

Brian

**Comment by Atreyuelguerrero** [comment]
> Lo molesto es que funcionó bien durante los últimos 6 meses. Tengo incluso de bios. Configure una ventana limpia sin usar. En una computadora portátil vieja. Nuevamente probé el archivo exe sin alegría. Debe ser del lado de Qobuz. Incluso intenté apagar todos los cortafuegos para probar esto. Espero que el desarrollador traiga una nueva versión, extraño mucho esto que estaba usando a diario
> 
> Gracias por tu ayuda
> 
> Saludos
> 
> Brian

El problema es que el que a tí te funcionaba hace 6 meses, ahora NO FUNCIONA, funciona el que he subido, que aunque parece el mismo, está parcheado. Yo lo hice como te he indicado y me funcionó a la primera. Yo trabajo con Windows 10. Desconozco, desde donde intentas ejecutarlo.

**Comment by Forlite** [comment]
> > https://github.com/ImAiiR/QobuzDownloaderX/files/8735127/QobuzDownloaderX.zip
> 
> Hi
> 
> Thank you for file, unfortunately I think that was the file I was using version 0.9.9.23.
> 
> I have tried and am still unable to log on, please find the error report
> 
> kind regards.
> 
> Brian
> 
> Error Log System.NullReferenceException: Object reference not set to an instance of an object. at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

This program is working perfectly! The problem is your account!!
You can use any account except your account to check with this program! 
![Screenshot (204)](https://user-images.githubusercontent.com/108256507/175874687-7e958cbd-ba1a-4a99-bac6-2f67d339fae2.jpg)
