### ISSUE TITLE
Patch works on one pc but not older pc

### ISSUE THREAD

**Issue by b1hwc** [ImAiiR/QobuzDownloaderX#124]
So i downloaded the fix per post 116, and still have issues with connecting.  I tried on aother PC and it works.   Cant figure out what issue is.  Removed and  downloaded again,  same issue.  Turned off firewall same issue.  Any ideas?

**Comment by CreaGab** [comment]
> So i downloaded the fix per post 116, and still have issues with connecting. I tried on aother PC and it works. Cant figure out what issue is. Removed and downloaded again, same issue. Turned off firewall same issue. Any ideas?

Please login normally on play.qobuz.com, then use alternative login methode: https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)
