### ISSUE TITLE
Support facebook login

### ISSUE THREAD

**Issue by Oscarz90** [ImAiiR/QobuzDownloaderX#125]
I used facebook to login so I'm not pretty sure about how to use this lib using FB login

**Comment by CreaGab** [comment]
> I used facebook to login so I'm not pretty sure about how to use this lib using FB login

Please log in to play.qobuz.com, then use the alternative login methode: https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)
