### ISSUE TITLE
I need help with login

### ISSUE THREAD

**Issue by asieczek334** [ImAiiR/QobuzDownloaderX#128]
I used program for few days and everything was fine. Today wanted login and i can't. I see this:
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()
   
   Is there anyway to solve it?

**Comment by zhangzl85** [comment]
Me 2

**Comment by roiosdonos** [comment]
Hi, I have problem with login in too..

Following Error:

System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

Is there a solution ?

Thanks to everyone

**Comment by Ammigo1** [comment]
Hi, Hello, I also have a problem logging in from today..
Following Error:

System.NullReferenceException: Object reference not set to an instance of an object.
at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()

Can anyone help with a solution?

Thanks to everyone

**Comment by ImAiiR** [comment]
Alright, looks like they just changed the javascript file, the regex that was used to get the App ID had changed up.

So changing line 392 in "LoginForm-v2.cs" should fix the login issue if building it yourself. Remember the App Secret that was done from another user as well to make sure it's working. Someone else can make a new working build if they'd like, as I'm still focusing on the rewrite, which I got logging in again.

I'll see if I can work on the original version a bit to make things easier, but it's been a bit, lol

Change line 392 in "LoginForm-v2.cs" 
From - `var bundleLog0 = Regex.Match(getBundleRequest, "\\):\\(n.qobuzapi={app_id:\"(?<appID>.*?)\",app_secret:").Groups;`
To - `var bundleLog0 = Regex.Match(getBundleRequest, "production:{api\\:{appId:\"(?<appID>.*?)\",appSecret:").Groups;`

**Comment by ImAiiR** [comment]
And I'm back again just to say it ***should*** be fixed up in the new update, cracked open the old project to quickly patch those issues up. Let me know if there's anything else broken in it.

https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.24

**Comment by asieczek334** [comment]
Thanks <3 it works

**Comment by Ammigo1** [comment]
Great, it works, thank you

**Comment by mcquadederwolf** [comment]
Bei mir funktioniert leider immer noch nicht.
