### ISSUE TITLE
Error when downloading a track from an album that is unavailable.

### ISSUE THREAD

**Issue by nath2125** [ImAiiR/QobuzDownloaderX#131]
![image](https://user-images.githubusercontent.com/99367069/227948243-941900c8-4cc7-4294-8c08-1e07809393ab.png)

Hi there and love the platform btw, but I'm getting this error message when downloading a whole album and a track in the middle of it being unavailable it skips the rest of them at the bottom.

**Comment by DerMuffin** [comment]
same

**Comment by nath2125** [comment]
Will there be a fix on this?
