### ISSUE TITLE
Can't login?

### ISSUE THREAD

**Issue by YuunaChan123** [ImAiiR/QobuzDownloaderX#135]
Hello! I keep having this error whenever I try to login with QBDLX. (I use user_id and auth-token for trying to login)

[Latest_Error.log](https://github.com/ImAiiR/QobuzDownloaderX/files/11241013/Latest_Error.log)

Any idea on how to fix it? I tried to use mods or forks made by others but it still won't work for me so I'll just stick with the main version first

**Comment by MarshallZPie** [comment]
I'm having the same issue :/

**Comment by italianjob79** [comment]
same here, no luck :(

**Comment by italianjob79** [comment]
it worked using ID and Token 👍
