### ISSUE TITLE
Why can I not get 5.1 downloads please?

### ISSUE THREAD

**Issue by neilwilkes** [ImAiiR/QobuzDownloaderX#139]
Hello.
I have just attempted to download what should be a 5.1 set - yet it has only come through in stereo.
[(https://play.qobuz.com/album/cjlqnpc1lenla)]

How can I get the 5.1 download properly please? There seems to be no option to select this, only resolution & file type.

**Comment by averyfollett** [comment]
How can you tell this is a 5.1 release? I'm not aware of Qobuz offering those.
If it is 5.1 then maybe try the official Qobuz downloader?
