### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mallikh67** [ImAiiR/QobuzDownloaderX#14]
hi using it  for a couple of days but now its not working shows login falied . can u sole this issue

**Comment by ImAiiR** [comment]
First, try logging in using the other method, and see if that works. If it doesn't, send the contents of "Latest_Error.log"

**Comment by mallikh67** [comment]
hi here is the log error generated. using the same user name and pwd ale to login to qobiz .

[Latest_Error.log](https://github.com/ImAiiR/QobuzDownloaderX/files/4675184/Latest_Error.log)

**Comment by 1claudiobruno** [comment]
yesss same problem:

Starting Downloads...

Failed to download (First Phase). Error information below.

System.ArgumentException: Caratteri non validi nel percorso.
   in System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.GetFullPathInternal(String path)
   in System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   in System.IO.Directory.CreateDirectory(String path)
   in QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__91.MoveNext()

**Comment by sergeochre** [comment]
The same error : 

Starting Downloads...

Failed to download (First Phase). Error information below.

System.ArgumentException: Путь содержит недопустимые знаки.
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.GetFullPathInternal(String path)
   в System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   в System.IO.Directory.CreateDirectory(String path)
   в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__91.MoveNext()

**Comment by sergeochre** [comment]
Search is not working as well

**Comment by ciaranvisuals** [comment]
It only seems to happen with discogs and albums downloading each induvidual track seems to still work

**Comment by ciaranvisuals** [comment]
Its actually only anything above 44.1/16

**Comment by ImAiiR** [comment]
> hi here is the log error generated. using the same user name and pwd ale to login to qobiz .
> 
> [Latest_Error.log](https://github.com/ImAiiR/QobuzDownloaderX/files/4675184/Latest_Error.log)

See if you're able to login using the alternative method - https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)

**Comment by mallikh67** [comment]
no not ale to login using alternate method also

**Comment by ImAiiR** [comment]
First thing to do, make sure your version is up to date. I just updated it, and fixed the downloading issues. This should fix most issues others are having. https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.14

For the login issue, check these things.

- Check if your computer's clock is set to the proper time, this can cause issues if not set properly.
- Double check all of your information when logging in through both methods.

The error you get isn't from the program, it's from trying to login to Qobuz. Qobuz is returning a 401 error, which usually happens when the information is wrong. The alternate login method is the best bet for getting logged in correctly, as some users have issues with the default login method. I can't think of anything else at the moment.

**Comment by mallikh67** [comment]
downloaded latest  version and same user name and pwd when logged in to
qobuz its working

but his app not working showing this error log

System.Net.WebException: The remote server returned an error: (401)
Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender,
DoWorkEventArgs e)

**Comment by 1claudiobruno** [comment]
great! it work! i buy you a coffe... thnx

**Comment by ImAiiR** [comment]
> downloaded latest version and same user name and pwd when logged in to qobuz its working
> 
> but his app not working showing this error log 
> 
> System.Net.WebException: The remote server returned an error: (401) Unauthorized. at System.Net.HttpWebRequest.GetResponse() at QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)

This is the same error that you were having before. I'm unable to help here, as the only suggestions I have are logging in the alternative way and checking your info is correct. As far as I can tell the issue isn't caused by the program.

**Comment by mallikh67** [comment]
hi its working thanks

regards
