### ISSUE TITLE
Error log in

### ISSUE THREAD

**Issue by htmenX** [ImAiiR/QobuzDownloaderX#144]
always Getting App ID and Secret  0.9.9.24 pls help

**Comment by Wang1998822** [comment]
I also have the same problem

**Comment by pinyht** [comment]
same problem

**Comment by hatebass** [comment]
是的，我也是无法登陆！

**Comment by learningmakesbetter** [comment]
same problem,also other download software like Allosoft can not log in .i guess Qobuz has banned all downloaders.
