### ISSUE TITLE
Client is downloading "Fake" flac?

### ISSUE THREAD

**Issue by koopa990** [ImAiiR/QobuzDownloaderX#146]
Has anybody noticed this issue? Screenshot from one of the disingenuous track in an album.
![sdfdsaf](https://github.com/ImAiiR/QobuzDownloaderX/assets/63154730/1caf4084-ee6d-4a03-8b31-5e43dbad9384)

**Comment by pstngh** [comment]
hey, did you dig any further on this ? was it a one off?
