### ISSUE TITLE
QBDLX only downloads preview tracks?

### ISSUE THREAD

**Issue by koopa990** [ImAiiR/QobuzDownloaderX#148]
I'm not sure if this tool actually needs my account to be premium?

**Comment by onlyFLAC** [comment]
And it's the same for me...

**Comment by koopa990** [comment]
> And it's the same for me...

in the meantime, im using a hidden bot tool in my discord that does the job well.

**Comment by 3Dieuwer** [comment]
Make sure that when u sign in it says 'Offer Type: Studio' and not free.
![image](https://github.com/ImAiiR/QobuzDownloaderX/assets/69723854/031d2f87-1b4e-4712-a63a-e9277a18b7ae)

**Comment by onlyFLAC** [comment]
![Screenshot 2024-04-06 231811](https://github.com/ImAiiR/QobuzDownloaderX/assets/162027426/c3a5749b-db5f-4ad9-aa0a-3d2976e66bc1)
But the problem remains...

> Убедитесь, что при входе в систему написано «Тип предложения: Студия» и не бесплатно. ![образ](https://private-user-images.githubusercontent.com/69723854/319516514-031d2f87-1b4e-4712-a63a-e9277a18b7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Mjc2MzgsIm5iZiI6MTcxMjQyNzMzOCwicGF0aCI6Ii82OTcyMzg1NC8zMTk1MTY1MTQtMDMxZDJmODctMWI0ZS00NzEyLWE2M2EtZTkyNzdhMThiN2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDE4MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNTBhMTIwMTJiYjEyMDY4ZDk5NGQwZWI0ZWZhMjQ4MDc1ZDQwNzAzZmQzYTk0MzgyNDVmMmVkMGVlOTZjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_tAo9w3mLjRqfAGQGaF9i5cM6DRrn6WK7SpuDPh5Sw)

**Comment by 3Dieuwer** [comment]
> > Make sure that when u sign in it says 'Offer Type: Studio' and not free. ![image](https://private-user-images.githubusercontent.com/69723854/319516514-031d2f87-1b4e-4712-a63a-e9277a18b7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzM1ODIsIm5iZiI6MTcxMjc3MzI4MiwicGF0aCI6Ii82OTcyMzg1NC8zMTk1MTY1MTQtMDMxZDJmODctMWI0ZS00NzEyLWE2M2EtZTkyNzdhMThiN2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTczY2NjNTU3NzVjYmQwYTJiMDkxNzEwODUxNWFjYjY4Yjc5YWViZTViZjY1NzI3Y2ZlZWU1ZjliMGYwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TsUGhkPygEhl0r0-guflHsljwZLr_f5DcV7ANIJYhAk)
> 
> I must have mistaken the purpose of this tool then. So sorry!

It happens. Please close the issue.
