### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by NicolasZiegler** [ImAiiR/QobuzDownloaderX#15]
Hi, today the software is not working anymore
Here is the notification when I download one track

Downloading - 01 -  ......

Track Download ERROR. Information below.

System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadTrackBG_DoWork>d__88.MoveNext()

I have downloaded this track yesterday without any problem, but today is not.
Please fix it

**Comment by ImAiiR** [comment]
Please test the new version and let me know if the issue is fixed.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.14

**Comment by NicolasZiegler** [comment]
Thanks a lot. The new version is working well.
