### ISSUE TITLE
bject sender, DoWorkEventArgs e) error

### ISSUE THREAD

**Issue by Gracefulmender** [ImAiiR/QobuzDownloaderX#157]
The app never opens up. Only giving me this error when I enter after putting in the correct login information.

**Comment by ImAiiR** [comment]
Could you share the contents of the latest_error file if there’s anything inside of it?

**Comment by Gracefulmender** [comment]
No, and the application will not get past the login screen.

**Comment by ImAiiR** [comment]
So if I’m understanding you correctly, this is what is happening.

- You open the program
- Login form appears
- You input your email and password
- Click login
- Program crashes with that error

is this correct?

**Comment by onlyFLAC** [comment]
Hi! I have this error that in the old and new versions...

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()

**Comment by onlyFLAC** [comment]
None of the methods work for me :(

**Comment by Gracefulmender** [comment]
> So if I’m understanding you correctly, this is what is happening.
> 
> * You open the program
> * Login form appears
> * You input your email and password
> * Click login
> * Program crashes with that error
> 
> is this correct?

yes

**Comment by ImAiiR** [comment]
Please give the new version a try and let me know if it works for you now!
