### ISSUE TITLE
[Bug] User info returning null on main form load after login

### ISSUE THREAD

**Issue by Ammigo1** [ImAiiR/QobuzDownloaderX#159]
513 / 5 000
A warning message will appear after logging into QBDLX_1.0.0.0 or 1.0.0.1. Microsoft .NET Framework
"An unhandled exception occurred in an application component. If you click the Continue button, the application will ignore this error and try to continue..... "
As soon as I press continue, everything seems to work as it should. But I would like to know why I am getting this warning.

(Windows 11 Pro 24H2 + QBDLX_1.0.0.1)

![Microsoft  NET Framework](https://github.com/user-attachments/assets/5d1961d7-4464-4738-bbb4-0d6570b33f3c)

Thank you

List of message details:

> Informace o vyvolání ladění JIT najdete na konci této zprávy,
> nikoli v tomto dialogovém okně.
> 
> ************** Text výjimky **************
> System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
>    v QobuzDownloaderX.qbdlxForm.qbdlxForm_Load(Object sender, EventArgs e)
>    v System.Windows.Forms.Form.OnLoad(EventArgs e)
>    v System.Windows.Forms.Form.OnCreateControl()
>    v System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    v System.Windows.Forms.Control.CreateControl()
>    v System.Windows.Forms.Control.WmShowWindow(Message& m)
>    v System.Windows.Forms.Control.WndProc(Message& m)
>    v System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    v System.Windows.Forms.ContainerControl.WndProc(Message& m)
>    v System.Windows.Forms.Form.WmShowWindow(Message& m)
>    v System.Windows.Forms.Form.WndProc(Message& m)
>    v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by ImAiiR** [comment]
If it’s still working as intended after hitting ignore, that’s better than it was before, but I will look into it. It seems something is returning a null value when loading the main form, just have to try to figure out what exactly it is when I get back from work.

**Comment by ImAiiR** [comment]
Will send this here as I already put it in the other issue.
Can you confirm if the about page on the main form includes all of the info? I haven't been able to pinpoint the issue, since all of my accounts and others I know don't get this popup.

Pushing a new update here in a bit, but doubt it will resolve this specific new issue.

**Comment by Ammigo1** [comment]
I tried version 1.0.0.2 and the problem still persists. Unfortunately. 
The program after starting, as it seems, but functions correctly.

Here is the transcript of the new message, it is only slightly different:

Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v QobuzDownloaderX.qbdlxForm.qbdlxForm_Load(Object sender, EventArgs e)
   v System.Windows.Forms.Form.OnLoad(EventArgs e)
   v System.Windows.Forms.Form.OnCreateControl()
   v System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   v System.Windows.Forms.Control.CreateControl()
   v System.Windows.Forms.Control.WmShowWindow(Message& m)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   v System.Windows.Forms.ContainerControl.WndProc(Message& m)
   v System.Windows.Forms.Form.WmShowWindow(Message& m)
   v System.Windows.Forms.Form.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

**QobuzDownloaderX**
    **Verze sestavení: 1.0.0.2**
    **Verze Win32: 1.0.0.2**
    **Základ kódu (CodeBase): file:///D:/!!!System/!!Portable/Qobuz%20Downloader%20X/QobuzDownloaderX.exe**

System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9256.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9266.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

**Qo(penAPI)**
    **Verze sestavení: 0.0.3.1**
    **Verze Win32: 0.0.3.1**
    **Základ kódu (CodeBase): file:///D:/!!!System/!!Portable/Qobuz%20Downloader%20X/Qo(penAPI).DLL**

System.Net.Http
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

Newtonsoft.Json
    Verze sestavení: 13.0.0.0
    Verze Win32: 13.0.3.27908
    Základ kódu (CodeBase): file:///D:/!!!System/!!Portable/Qobuz%20Downloader%20X/Newtonsoft.Json.DLL

mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll

System.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.resources.dll

System.Numerics
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9241.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Data
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9214.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll


************** Ladění JIT **************
Aby bylo povoleno ladění JIT, musí konfigurační soubor
pro tuto aplikaci nebo počítač (machine.config) mít
v oddílu system.windows.forms nastavenou hodnotu njitDebugging.
Aplikace rovněž musí být kompilována s povoleným
laděním.

Příklad:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Je-li ladění JIT povoleno, budou všechny neošetřené výjimky
odeslány ladicímu programu JIT, který je registrován v počítači,
a nebudou zpracovány tímto dialogovým oknem.

**Comment by ImAiiR** [comment]
Are you able to check the about tab on the main form after logging in? Are all of the values listed correctly on that page? Trying to narrow down what response is returning null.

**Comment by Ammigo1** [comment]
Yes. I'll try as soon as I get home from work.

**Comment by vad62** [comment]
The error remained at 1.0.0.2

<img width="426" alt="Снимок экрана 2024-10-17 в 09 16 00" src="https://github.com/user-attachments/assets/72081262-8fdd-42d0-8c22-f2dcd625a41c">

**Comment by ImAiiR** [comment]
> The error remained at 1.0.0.2
> 
> <img alt="Снимок экрана 2024-10-17 в 09 16 00" width="426" src="https://private-user-images.githubusercontent.com/62072455/377338479-72081262-8fdd-42d0-8c22-f2dcd625a41c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzA1ODAsIm5iZiI6MTcyOTE3MDI4MCwicGF0aCI6Ii82MjA3MjQ1NS8zNzczMzg0NzktNzIwODEyNjItOGZkZC00MmQwLThjMjItZjJkY2Q2MjVhNDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEzMDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOTkwMDk3MzZmZjk5OWIwMWYzMGNhZDkxNTdiYzA4M2NhMjkzZjJmMDg2ZWJjZjliM2YwYTJhMzk1OGViZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bHqM_lU69_h-k_Dn_88kdxMMh36xI8Uwb9iinxATgUE">
> If you click "continue", then the application is loaded and works normally.

Same question for you as well. Can you check the about tab on the main for after hitting continue, and tell me if all of the values there are listed correctly?

**Comment by Ammigo1** [comment]
I am sending a copy of the screen. I hope I understood that correctly. One total. one detail.
![2024-10-17 15_39_13-qbdlxForm](https://github.com/user-attachments/assets/0c6ffa3d-3c72-4c71-92c0-b6f00e51ca1b)
![2024-10-17 15_39_44-qbdlxForm](https://github.com/user-attachments/assets/c6b95d20-c759-4b75-8f11-74899b8dd10d)

**Comment by ImAiiR** [comment]
Thank you, so something in the user info is returning null. Will get this patched up to try to avoid this error again.
If there's a chance, would you be willing to share login info for the account to see if I can recreate the issue? (Send privately, don't send it here, you can e-mail if needed)

**Comment by Ammigo1** [comment]
I'm very sorry. I'd like to, but I can't afford to send the account
credentials. This account is not just mine... I hope you understand why I
can't.  Thank you

čt 17. 10. 2024 v 15:46 odesílatel AiiR ***@***.***> napsal:

**Comment by ImAiiR** [comment]
All good, I understand. I will try to look more into it.
If anyone else having this issue has an account they can share for me to recreate this issue, let me know!

**Comment by ImAiiR** [comment]
I added more logging to the latest release, so I can get more detailed info on where issues happen.
If you guys are still getting the error, send me the logs! Can either use a paste site or send the file, either works.
Feel free to edit emails out of the logs if you feel the need.

**Comment by vad62** [comment]
In the new version 1.0.0.3 errors are not noticed, excellent job!

**Comment by AngelArturoDBLooper** [comment]
In the new version 1.0.0.3 the error of "System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.DownloadTrack.downloadTrack(String app_id, String album_id, String format_id, String audio_format, String user_auth_token, String app_secret, String downloadLocation, String artistTemplate, String albumTemplate, String trackTemplate, Album QoAlbum, Item QoItem)". It still persists

**Comment by ImAiiR** [comment]
> In the new version 1.0.0.3 the error of "System.NullReferenceException: Object reference not set to an instance of an object. at QobuzDownloaderX.DownloadTrack.downloadTrack(String app_id, String album_id, String format_id, String audio_format, String user_auth_token, String app_secret, String downloadLocation, String artistTemplate, String albumTemplate, String trackTemplate, Album QoAlbum, Item QoItem)". It still persists

Could you send me the logs for both the login form and QBDLX form after the error happens? Just sending the 2 files should work.

**Comment by Ammigo1** [comment]
Hello. It seems that in version 1.0.0.3 it already works as it should.  No unpleasant message when starting up appears anymore... I'm away from home now, so I'll try it on the other PC when I get back. Thank you for your patience.

**Comment by ImAiiR** [comment]
The latest version should fix this up completely, the issue was caused by accounts that were attached to family accounts.
If anyone gets this same error again, please re-open this!
