### ISSUE TITLE
not working!!!

### ISSUE THREAD

**Issue by maverick666666** [ImAiiR/QobuzDownloaderX#16]
not working!!! :(

**Comment by ciaranvisuals** [comment]
> 
> 
> not working!!! :(

send "Latest_Error.log"

**Comment by killy1980** [comment]
> ¡¡¡no funciona!!! :(

a mi tampoco me funciona "Failed to download (First Phase). Error information below." me sale

**Comment by ImAiiR** [comment]
When opening an issue, please provide all of the error information you can.

Please test the newest version and see if the issue is resolved.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.14

**Comment by maverick666666** [comment]
ya funciona GRACIAS CRACK!!!
