### ISSUE TITLE
Can't log in...

### ISSUE THREAD

**Issue by iamlight33** [ImAiiR/QobuzDownloaderX#161]
Hi! 

For months, everything was working fine in QBDLX-MOD & QBDLX, 
but now no ID / Token combinations are working for me neither in 
QBDLX 1.0.0.2 nor QBDLX-MOD 1.2.5.0, 1.2.6.0, or 1.2.7.0.

This is the error code in QBDLX-MOD 1.2.6.0 / 1.2.7.0:

Api response code: 400
Api response status: error
Api response reason: Invalid or missing app_id parameter. 

This is the error code in QBDLX-MOD 1.2.5.0:

Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

This is the error code in QBDLX 1.0.0.2:

System.NullReferenceException: The object reference was not set to an object instance.
   bei QobuzDownloaderX.LoginForm.loginBackground_DoWork(Object sender, DoWorkEventArgs e)

I am using the user_id / user_auth_token log in, but it's not working anymore...

Please help! Thanks in advance!

**Comment by konehomatt** [comment]
yep, here too
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginForm.loginBackground_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment]
If you're using a token from an account made before the recent Qobuz updates, you'll need a specific App ID and Token.
I can't share those values here directly, but you may be able to find the ones you need [here](https://telegra.ph/How-to-fix-403---Invalid-usernameemail-and-password-10-12)

Right back to me when you've tested this @iamlight33

**Comment by iamlight33** [comment]
WOW! That's awesome! All is working perfect again, amazing!
Thank you a zillion times more powerful each day for this great link!
'Account tools' seem to be not working for me, but 'Tmx's Helper Bot' is brilliant!
