### ISSUE TITLE
[Bug] Error when running on mac

### ISSUE THREAD

**Issue by gr3enarr0w** [ImAiiR/QobuzDownloaderX#163]
i get errors trying to run on mac
Build FAILED.

/usr/local/share/dotnet/sdk/8.0.403/Microsoft.Common.CurrentVersion.targets(1259,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/clarkeverson/Documents/QobuzDownloaderX-master/QobuzDownloaderX/QobuzDownloaderX.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.20
(base) clarkeverson@Clarks-MacBook-Air QobuzDownloaderX-master %

**Comment by ImAiiR** [comment]
This program is built to run on Windows, and I don’t have a Mac to try to test and run code on to see if I can get it running for Mac. At the moment this won’t be worked on by me, sorry. If anyone else would like to troubleshoot this, that would be great.
