### ISSUE TITLE
You can't choose DSD quality

### ISSUE THREAD

**Issue by avbc81** [ImAiiR/QobuzDownloaderX#164]
DSD quality albums have recently appeared https://www.qobuz.com/us-en/search/query/dsd-dxd-catalog  and this update is not in the program

**Comment by avbc81** [comment]
there is no such option in the player yet either

**Comment by ImAiiR** [comment]
![image](https://github.com/user-attachments/assets/0f4550b2-eec7-4e42-81d7-ae8bcf969e71)
You still can't stream DSD directly through the Qobuz web player, closing
