### ISSUE TITLE
[Bug] Tracks are downloaded into a generic FLAC folder when using the %FormatWithHiResQuality% template

### ISSUE THREAD

**Issue by Lazar-Razvan** [ImAiiR/QobuzDownloaderX#165]
Downloading a playlist using the template setting shown in the image below will download all playlist tracks into a single FLAC folder instead of multiple folders based on each track's quality (`FLAC (16bit-44.1kHz)`, `FLAC (24bit-44.1kHz)`, `FLAC (24bit-48kHz)` etc.)

![image](https://github.com/user-attachments/assets/ba49794c-a7a9-47b0-a14e-7deff48db84b)

**Comment by ImAiiR** [comment]
My main focus was never really playlists, so it’s possible that I messed something up. Do you have a public playlist link that your issue happens on that I can use for testing?

My guess before looking into my own code is that I didn’t want tracks to get unorganized into separate quality folders when downloading a playlist, so I probably made it generic.

**Comment by Lazar-Razvan** [comment]
Sure, you can use the following playlist: https://open.qobuz.com/playlist/6615927

**Comment by ImAiiR** [comment]
So it's definitely something I intended so the tracks wouldn't get super unorganized, But for an alternative, I've added `%TrackFormatWithHiResQuality%` as a track template option, so you can do something like the example below for the track template, and change your playlist template to whatever else. (This still has some issues, but haven't had the time to work them out yet)

Track template example - `%TrackFormatWithHiResQuality%\%TrackNumber% %TrackTitle%`

For now I will close this, as I don't plan to change the way playlist templates handle the `%FormatWithHiResQuality%` template
