### ISSUE TITLE
[Bug] Digital booklets (goodies) not downloading

### ISSUE THREAD

**Issue by ygj1988** [ImAiiR/QobuzDownloaderX#166]
Hi thx for hardwork, but new version without downloading booklet. hope can get back, thx so much

**Comment by ImAiiR** [comment]
Please give a release link that includes the booklet, and I'll check it.
Also just in case, if you wouldn't mind sending the log after it fails to download.

**Comment by ygj1988** [comment]
I just tried to download the link from you, yes, booklet downloaded. 
But when I try to download this,  [https://play.qobuz.com/album/hbjzxlctl3wgb](url)  not working. 
and may i know where to get the log ?

**Comment by ImAiiR** [comment]
Download does fail for that release, and I think I have a good idea as to why. Most likely the title of the file has illegal characters in the filename when attempting to save. Will get this fixed up in the next version.

As for finding the logs for QBDLX, you can find them in the "logs" folder in the same path as the QBDLX executable.

**Comment by ygj1988** [comment]
Thank you very much. I hope the issue can be fixed soon. Right now, I am still using the previous version to download the booklet.

**Comment by ImAiiR** [comment]
Should be all fixed up in the latest version! If there's still any issues, please re-open this!
