### ISSUE TITLE
[Feature Request] Display download speed and progress during download

### ISSUE THREAD

**Issue by MxqingDesign** [ImAiiR/QobuzDownloaderX#167]
Can the download process display the download speed and progress?
![photo_2024-10-26_20-15-15](https://github.com/user-attachments/assets/7f53c25a-9eb3-4967-afe1-6d057921e58f)

**Comment by ImAiiR** [comment]
Already have this working, will hopefully be working fully in next update!

**Comment by ImAiiR** [comment]
Should be working in the latest version!
