### ISSUE TITLE
[Feature Request] Add back the custom comment tagging option

### ISSUE THREAD

**Issue by Nikero066** [ImAiiR/QobuzDownloaderX#168]
it's a shame that the comment paragraph is missing

**Comment by ImAiiR** [comment]
I'm not sure what this means

**Comment by TheParaTiger** [comment]
He means this field at the bottom where you can put a comment in. You were able to use this to put something of your choice in.
![Screenshot 2024-10-27 214956](https://github.com/user-attachments/assets/c77e733e-f6d5-46f8-a510-941ad4c789c8)

**Comment by ImAiiR** [comment]
I was thinking that, could definitely add it back, and it shouldn't be too difficult. Will probably add it back in the next update

**Comment by Nikero066** [comment]
This was in the previous version

"Comment"



<img width="375" alt="{27509D6F-8F52-4C57-B98D-A7B5B279ACCE}" src="https://github.com/user-attachments/assets/3800bddb-cfed-4e6f-8b0a-4caf30470572">

**Comment by ImAiiR** [comment]
Yes, got it working again and will be available in the next update

**Comment by ImAiiR** [comment]
1.0.0.5 out now, let me know if there's any issues with the comment tagging!

**Comment by Nikero066** [comment]
Thank you, the comments are up.

**Comment by Nikero066** [comment]
I don't want to download playlists . 
Version 0.9.9.24 downloads everything ?

**Comment by ImAiiR** [comment]
> I don't want to download playlists . Version 0.9.9.24 downloads everything ?

If you don't want to download playlists you don't have to. I'm not sure if I'm understanding you correctly.
Also, if it doesn't relate to this specific issue, please create a new issue.
