### ISSUE TITLE
There is a lack of a layer to distinguish between hires or lossless folders

### ISSUE THREAD

**Issue by ygj1988** [ImAiiR/QobuzDownloaderX#169]
There is a lack of a layer to distinguish between hires or lossless folders。 if can keep it just like prevouse verison will be better.

**Comment by ImAiiR** [comment]
Use the templates `%Format%` or `%FormatWithHiResQuality%`

`%Format%` will always use "FLAC", no matter if it's 16/44.1 or 24/96 (for example)
`%FormatWithHiResQuality%` will use "FLAC" for standard 16/44.1, but will use "FLAC (24bit-96kHz)" for 24/96
