### ISSUE TITLE
[Feature Request] Add "FLAC (16bit-44.1kHz)" folder template

### ISSUE THREAD

**Issue by cboby1234** [ImAiiR/QobuzDownloaderX#170]
Can we increase？
%FormatWithHiResQuality% Can FLAC not be displayed

**Comment by ImAiiR** [comment]
Can probably add a new template, something like `%FormatWithQuality%` that will never use just "FLAC", but will always list the bit depth and rate, similar to how `%FormatWithHiResQuality%` works

**Comment by cboby1234** [comment]
Please do not add special symbol (), some people like [] or <>

**Comment by ImAiiR** [comment]
Could also possibly add a way to swap if you want to use () or [].

**Comment by cboby1234** [comment]
Now it's all Explicit, can it be simpler: [E]

**Comment by finegoober** [comment]
Was this issue resolved? The old program would have a sub folder labeled with type and quality, is this feature gone from the new version? If not, how do I add it again?

**Comment by ImAiiR** [comment]
> Was this issue resolved? The old program would have a sub folder labeled with type and quality, is this feature gone from the new version? If not, how do I add it again?

It was resolved, new templates were added, so you can customize your templates to your liking

**Comment by finegoober** [comment]
I'm on the newest (1.0.0.7) and don't know which one adds the subfolder with quality.

**Comment by ImAiiR** [comment]
For an example, let's say you download an album at FLAC 16bit/44.1kHz
Here's what these formats would add

`%Format%` = FLAC
`%FormatWithQuality%` = FLAC (16bit-44.1kHz)
`%FormatWithHiResQuality%` = FLAC

And if the album was FLAC 24bit/96kHz

`%Format%` = FLAC
`%FormatWithQuality%` = FLAC (24bit/96kHz)
`%FormatWithHiResQuality%` = FLAC (24bit/96kHz)

**Comment by ImAiiR** [comment]
The album template examples I gave you is what makes a subfolder for quality

**Comment by finegoober** [comment]
I'm a dummy. I couldn't get it the last couple times, but I figured it out.
Thanks!
