### ISSUE TITLE
[Feature Request] Add template for bit depth and sample rate

### ISSUE THREAD

**Issue by vad62** [ImAiiR/QobuzDownloaderX#171]
Hello! 
I didn't notice any difference between the tags:
%FormatWithQuality%, %FormatWithHiResQuality%
You can make a displayed template, only with quality, without format, as an example:
(24-44.1),(16-44.1)...

**Comment by ImAiiR** [comment]
If looking for templates for just bit depth and sample rate, I should definitely be able to add those in the next update!

As for differences for `%FormatWithQuality%` and `%FormatWithHiResQuality%`
`%FormatWithQuality%` - Will ALWAYS includes quality after "FLAC"
`%FormatWithHiResQuality%` - Will only include quality with hi-res releases

**Comment by ImAiiR** [comment]
Added the templates! Let me know if there's any issues with them
