### ISSUE TITLE
[Bug] QBDLX "forgets" custom comment setting upon restart of it

### ISSUE THREAD

**Issue by TheParaTiger** [ImAiiR/QobuzDownloaderX#172]
When i restart Qbdlx, the custom comments settings i took before get deleted and i have to redo them. Something like an .ini file that saves the settings you took would be useful as you also have to re-enter all the settings and log-in again after you update it. I update Qbdlx by overwriting the files with the new Version.

Ver: 1.0.0.5

To Reproduce:

1. Open Qbdlx, log-in and enable the custom comments section in the settings
2. Close Qbdlx
3. Start it again, log-in and you'll notice, that the custom comment section is disabled again and the custom comment being deleted.

Any other setting saves as expected, just not the custom comments section.

**Comment by ImAiiR** [comment]
Hmm, weird. Had it working with saving the settings while testing, but have been busy so maybe forgot to save something?
Will get it fixed up for next update, sorry about that!

**Comment by TheParaTiger** [comment]
Oh it's not that inconvenient or urgent, the rest works fine so no worries!

**Comment by ImAiiR** [comment]
Should be fixed in the new version! Re-open this if there's still any issue!

**Comment by TheParaTiger** [comment]
The issue has been fixed so thank you for that!

But in version 1.0.07, i've noticed that QBDLX stopped recognizing the %Description% Template but instead puts this in the comment section instead of the actual description of the Album. This works as intended with 1.0.0.6 but somehow broke in 1.0.0.7. (Maybe because of your partial rewrite?).

Another strange thing i noticed is that Qbdlx forgets it's settings when you rename the folder where it is in, but when i rename it back to the name i had before the settings magically reappear, idk what's up with that xD.

**Comment by ImAiiR** [comment]
- For the `%Description%` issue, yeah, that was on me, forgot the naming I used on templates starts with a capital letter for them, whoopsies. Temporary solution is to use `%description%` instead. Will make sure that also continues to work later on, probably find a way to make them not case sensitive, but too tired to do that right now.
- For the settings getting cleared when renaming the folder, yeah, that's just how the program saves settings, it remembers the path. You can always copy over the config file from your `%localappdata%\AiiR\QobuzDownloaderX.exe_Url_randomstringhere`, run the program from the new folder (or renamed folder), and then paste the old config in the newly created folder inside of `%localappdata%\AiiR\QobuzDownloaderX.exe_Url_NEWrandomstringhere`.

**Comment by TheParaTiger** [comment]
I see thanks!
I just downgraded to 1.0.0.6 for the time xD
