### ISSUE TITLE
[Feature Request] Add a Light Mode Option

### ISSUE THREAD

**Issue by MichaelDewis** [ImAiiR/QobuzDownloaderX#173]
No problems with usage .. it works well. Thank you.
However my aging eyes have a problem with the dark mode.
Is there a way of changing it?

**Comment by ImAiiR** [comment]
Maybe at some point in the future I could add this, at the moment though this will be a future plan. Thanks for the suggestion!

**Comment by MichaelDewis** [comment]
No worries. It works extremely well, and that is what matters.

**Comment by ImAiiR** [comment]
Throwing a preview here, as I decided to go ahead and work on this, lol
![theming-2024-11-5](https://github.com/user-attachments/assets/6373626c-38e2-4dc7-8df0-e1a4b1c04632)

**Comment by MichaelDewis** [comment]
Looks good and for my eyes, very much easier to read. No fancy fonts or
colours required, just plain. I like the new logo by the way.

**Comment by ImAiiR** [comment]
Added in the new version!
