### ISSUE TITLE
[Feature Request] Other language translations

### ISSUE THREAD

**Issue by jota726** [ImAiiR/QobuzDownloaderX#175]
I could add more languages ​​like Spanish

**Comment by ImAiiR** [comment]
I'll begin work on adding language options. Will only include English on release of it, but then users who want to can translate it into different languages, and I can add them in.

**Comment by MxqingDesign** [comment]
> I'll begin work on adding language options. Will only include English on release of it, but then users who want to can translate it into different languages, and I can add them in.

I can provide language translation for Simplified Chinese.

**Comment by ImAiiR** [comment]
1.0.0.8 is out now, which supports languages. If you'd like to create your own translations, you can duplicate the `en.json` file, and do your translations. Please no AI or Google Translate translations.

Closing this as support was added, create new issues for submitting languages!
