### ISSUE TITLE
Qobux User password Issue

### ISSUE THREAD

**Issue by mustafamutlu29** [ImAiiR/QobuzDownloaderX#176]
Hello,

3 weeks ago the app was updated and I downloaded the new version but it asks for username and password, which I don't have. Can you help me how to do it?

![log](https://github.com/user-attachments/assets/2e72c109-db8e-4870-9561-590476220732)

**Comment by ImAiiR** [comment]
You need a Qobuz account with an active paid subscription for QBDLX to work. The email and password login is for your Qobuz account info. If you have an account token you can login with that instead by choosing “Login with token”.
