### ISSUE TITLE
[Bug] Unable to write files

### ISSUE THREAD

**Issue by aleksnett** [ImAiiR/QobuzDownloaderX#177]
Program does not want download anything /Write in log file  
Album Download Task ERROR.
System.IO.IOException: The media is write protected.

**Comment by ImAiiR** [comment]
My first assumption is a permissions issue. Try either running the program on a different drive, or run the program as admin. I haven’t seen this error happen for users before.

**Comment by ImAiiR** [comment]
No follow up for now, so closing this. If this is still a problem, please re-open this issue.
