### ISSUE TITLE
[Feature Request] Add russian language (ru.json)

### ISSUE THREAD

**Issue by Kuzmich55** [ImAiiR/QobuzDownloaderX#178]
Hello,
I have translated the application into Russian. Where should I place the ru.json file so that I can easily update and add it to the source code in the future?

**Comment by ImAiiR** [comment]
Can add the file to this issue, and I'll test it out, see if there's anything that I need to change design wise. Will probably add a way for languages to auto-update when QBDLX is run, but for now, manually adding to the folder.

**Comment by Kuzmich55** [comment]
In some places, mainly on buttons and fields of a specific size, I had to shorten the phrases or switch from uppercase to lowercase letters to fit the text.
Some fields don't have entries in the resource file, so they cannot be translated. (FAVORITES TEMPLATE; TEMPLATES LIST)

Fields where the phrase in Russian was shortened while maintaining the meaning:

```
"additionalSettingsButton": "Additional Settings",
"additionalSettingsButton": "Additionally",

"closeAdditionalButton": "Back to Settings",
"closeAdditionalButton": "Back",

"openFolderButton": "Open Folder",
"openFolderButton": "Open",

"qualitySelectButton": "Quality Selector",
"qualitySelectButton": "Quality",

"selectFolderButton": "Select Folder",
"selectFolderButton": "Select",
```

Fields where the letters were switched from uppercase to lowercase:

```
"downloadButton": "GET",
"searchAlbumsButton": "RELEASES",
"searchTracksButton": "TRACKS",
```

The MD5 correction also works (Windows 10) if flac.exe is placed in the same folder as the executable file or if a relative symbolic link is created. This might be worth mentioning in the MD5 correction function description.

[ru.json.zip](https://github.com/user-attachments/files/17825862/ru.json.zip)

**Comment by Kuzmich55** [comment]
Additionally, the Russian font doesn't look very good, especially the difference is noticeable in the screenshot.

![Default](https://github.com/user-attachments/assets/b6acacca-ef96-4965-a79b-b3540c616a4e)

**Comment by ImAiiR** [comment]
> In some places, mainly on buttons and fields of a specific size, I had to shorten the phrases or switch from uppercase to lowercase letters to fit the text.

I knew this would most likely be an issue in different languages, glad you were able to shorten things to get them to fit, but I’ll still look into updating the design to be more friendly for longer translations.

> Some fields don't have entries in the resource file, so they cannot be translated. (FAVORITES TEMPLATE; TEMPLATES LIST)

If you’d like, send me the translations for these, and I’ll add them, seems I had forgotten them. (Favorites currently goes unused, so may remove that, we will see)

> The MD5 correction also works (Windows 10) if flac.exe is placed in the same folder as the executable file or if a relative symbolic link is created. This might be worth mentioning in the MD5 correction function description.

Good to know! I remember having someone test, and even when it was in the same path as QBDLX, it didn’t work, so it seems to be a bit weird depending on the user/setup

> Additionally, the Russian font doesn't look good, especially the difference is noticeable in the screenshot.

Will see if I can add a way for the font to be changed in the JSON file, so that the translator can choose a better font if needed. Can’t promise this one yet, but if I can do it, I’ll include it!

**Comment by Kuzmich55** [comment]
> If you’d like, send me the translations for these, and I’ll add them, seems I had forgotten them. (Favorites currently goes unused, so may remove that, we will see)

Translation of these two lines below.

FAVORITES TEMPLATE = ШАБЛОН ИЗБРАННОГО
TEMPLATES LIST = СПИСОК ШАБЛОНОВ

I plan to continue providing support for the app's Russian localization in the future.
Keep in touch.

**Comment by ImAiiR** [comment]
Alright, so I've done a few updates, have your translation working & updated with the translations I had forgotten, along with the ability to use a different font. I've used the font "Segoe UI Symbol", do you think this font looks a bit better? Don't want to push the update with a bad font choice, lol.

![languages-2024-11-20](https://github.com/user-attachments/assets/64622921-5341-43d3-9e3d-83ea6002944e)

**Comment by ImAiiR** [comment]
Segoe UI does look a bit better, at least to me, will use that for now unless a better font is found.
Update will be pushed soon and this language will be included, thanks!

**Comment by ImAiiR** [comment]
Added to 1.0.0.9!
