### ISSUE TITLE
[Feature Request] Add Simplified Chinese Language

### ISSUE THREAD

**Issue by MxqingDesign** [ImAiiR/QobuzDownloaderX#179]
![01](https://github.com/user-attachments/assets/a153371f-17bd-41f6-9a84-8b1720970e3a)
![02](https://github.com/user-attachments/assets/ed56ac69-196a-4742-9eb9-edf45036dfb2)
![03](https://github.com/user-attachments/assets/b930f0a7-141e-4e5e-9138-a8e299260f1a)
![04](https://github.com/user-attachments/assets/6d6107d6-9b66-416d-b23e-9ad8cd35edf7)
![05](https://github.com/user-attachments/assets/c9dda01a-01b5-448e-a787-ebd732686e2a)

Translated according to the Simplified Chinese standard in Microsoft's Localization Style Guide. The font size on the translated interface looks a bit large. It is recommended to optimize the font size.

https://learn.microsoft.com/en-us/globalization/reference/microsoft-style-guides

[zh-CN.json](https://github.com/user-attachments/files/17848029/zh-CN.json)

**Comment by ImAiiR** [comment]
A few things for the next update, missing translations and font choice,

- Need a translation for "TEMPLATES LIST"
- Need a translation for "FAVORITES TEMPLATE"
- If you know of a better default Windows font choice, I can give it a test to see how it looks!

**Comment by MxqingDesign** [comment]
> A few things for the next update, missing translations and font choice,
> 
> * Need a translation for "TEMPLATES LIST"
> * Need a translation for "FAVORITES TEMPLATE"
> * If you know of a better default Windows font choice, I can give it a test to see how it looks!

"TEMPLATES LIST": “模板列表”
"FAVORITES TEMPLATE": “收藏模板”

**Comment by ImAiiR** [comment]
I've set the font to `Microsoft YaHei UI` for this translation, hoping that looks at least a tiny bit better, will be pushing the update soon, and will include this language option!
![2024-11-22-languages](https://github.com/user-attachments/assets/40c2f0c8-2de0-4de2-a9c6-5fafe0667caf)

**Comment by ImAiiR** [comment]
Added to 1.0.0.9!
