### ISSUE TITLE
Corregir No Funciona a partir de ayer

### ISSUE THREAD

**Issue by killy1980** [ImAiiR/QobuzDownloaderX#18]
No funciona siguiente error
Failed to download (First Phase). Error information below.

System.ArgumentException: Caracteres no válidos en la ruta de acceso.
   en System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   en System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   en System.IO.Path.GetFullPathInternal(String path)
   en System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   en System.IO.Directory.CreateDirectory(String path)
   en QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__91.MoveNext()

**Comment by ImAiiR** [comment]
Please test the newest version and let me know if the issue is fixed.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.14
