### ISSUE TITLE
[Feature Request] "Open Folder" option on main screen

### ISSUE THREAD

**Issue by MichaelOHInTO** [ImAiiR/QobuzDownloaderX#181]
Hello! 

Many thanks for all you do.  

Can you possibly add the "open folder" back to the main screen?

**Comment by ImAiiR** [comment]
Sorry for late response!
Is there any other reasons for this change other than ease of access? I don't think it make much difference between adding it to the main screen, and quickly swapping to the settings to open the download folder.

**Comment by MichaelOHInTO** [comment]
Hey there, 

No other reason except that I am lazy - so no worries at all. 

Haha.  

Thanks again for everything - I use your program ALL THE TIME! 

Michael 
    On Tuesday, December 3, 2024 at 10:06:39 a.m. EST, AiiR ***@***.***> wrote:  
 
 


Sorry for late response!
Is there any other reasons for this change other than ease of access? I don't think it make much difference between adding it to the main screen, and quickly swapping to the settings to open the download folder.

**Comment by ImAiiR** [comment]
Understood lmao. Happy you enjoy the program! Probably won't add the extra button for now, unless I want to make some design changes in the future.
