### ISSUE TITLE
How can I get the appid！！！！！！

### ISSUE THREAD

**Issue by ZPH666666** [ImAiiR/QobuzDownloaderX#2]
How can I get the appid？
Please help me

**Comment by ImAiiR** [comment]
1. Go to https://play.qobuz.com/
2. Login (if you aren't already logged in)
3. Open your browser's "Developer Tools" menu. (get to "Inspect Element" for example)
4. Click on the "Network" tab.
5. Refresh the page
6. Click on one of the more recent responses that have been listed.
7. On the side menu, make sure you're on the "Headers" tab.
8. Look for "X-App-Id", and the value you need should be next to that.
9. If the "X-App-Id" value isn't shown, try another response on the list. It will be in at least one of them, so keep trying, and you'll find it eventually.

![Untitled](https://user-images.githubusercontent.com/22158489/72656125-55ac6e80-3967-11ea-8745-56a63e30c601.jpg)

**Comment by drutten2** [comment]
How do I get the secret ID? needed also
