### ISSUE TITLE
DL error goodies

### ISSUE THREAD

**Issue by Hirsch2k1** [ImAiiR/QobuzDownloaderX#23]
I get an 404 on 99.14 every time there are goodies to download:

 bei System.Net.WebClient.DownloadFile(Uri address, String fileName)
   bei QobuzDownloaderX.QobuzDownloaderX.<downloadLabelBG_DoWork>d__88.MoveNext()

I just bought you a coffee, awesome work :)

**Comment by ImAiiR** [comment]
Fixed! I knew I forgot to fix something. Thanks for the coffee!
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.15
