### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mallikh67** [ImAiiR/QobuzDownloaderX#28]
hi latest version of qbdlx 0.9.9.15 not working. shows this error message when trying to download

System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment]
504 errors are just timeouts while trying to connect. Usually just trying again fixes it, but if that doesn't, check your internet connection, make sure your computer's clock is synced properly, check VPN connection if using one, etc.

If you fix it or get a different error, let me know.

**Comment by diegoborgh** [comment]
Looks like it stopped working again
