### ISSUE TITLE
I have a question about Qobuz accounts

### ISSUE THREAD

**Issue by leunamemar** [ImAiiR/QobuzDownloaderX#29]
A question:
I am from Peru (South America), will I always have to use a VPN software?
I am telling you this because I created a temporary account that gives me 1 month free, but it has fallen in just 10 days.

Thanks for the guide and help.

**Comment by ImAiiR** [comment]
If you can't get an account where you live, you will need to use a VPN to make an account you can use. You most likely won't need to be connected to a VPN to sign in and use it though.

**Comment by leunamemar** [comment]
> 
> 
> If you can't get an account where you live, you will need to use a VPN to make an account you can use. You most likely won't need to be connected to a VPN to sign in and use it though.

ok.. thank you for you help!!
