### ISSUE TITLE
Still unable to log in

### ISSUE THREAD

**Issue by ZPH666666** [ImAiiR/QobuzDownloaderX#3]
![捕获](https://user-images.githubusercontent.com/53807952/72656421-05b8c080-39d6-11ea-9670-a40f03923c8e.JPG)
I've entered the appid, but I still can't log in or download the song

**Comment by ImAiiR** [comment]
Go to the location of the QBDLX program, there should be an error log. Show me what the log says.

**Comment by ZPH666666** [comment]
System.Net.WebException: remote server return error: (401) unauthorized.

At System.Net.HttpWebRequest.GetResponse ()

In QobuzDownloaderX. LoginFrm. LoginBG_DoWork (Object sender, DoWorkEventArgs e)

**Comment by ZPH666666** [comment]
The original:System.Net.WebException: 远程服务器返回错误: (401) 未经授权。
   在 System.Net.HttpWebRequest.GetResponse()
   在 QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment]
That usually means your email or password was wrong before. Double check that your password is correct before you hit "MD5", then try again. If you want, just type your password somewhere, and then just copy and paste it there. If it still fails, it's possible your password for the account isn't what you think it is. Try changing it. Let me know if that works for you.

I'll be making an update adding a checkbox to make the password visible so you can double check.

**Comment by ImAiiR** [comment]
It's been over 10 days, I'll assume the issue is resolved. Update will come when I have time to do it.

**Comment by ZPH666666** [comment]
I have tried many times these days, but nothing works, so I give up




| |
18005881511
|
|
邮箱：18005881511@163.com
|

Signature is customized by Netease Mail Master

On 01/29/2020 15:04, AiiR wrote:

It's been over 10 days, I'll assume the issue is resolved. Update will come when I have time to do it.
