### ISSUE TITLE
Problem with The Beatles track

### ISSUE THREAD

**Issue by fominator** [ImAiiR/QobuzDownloaderX#31]
From Abbey Road (Super Deluxe Edition)

I assume track name is too long. Need some kind of fix.

Downloading - 09 - The Long One (Comprising of ‘You Never Give Me Your Money’, ’Sun King’/’Mean Mr Mustard’, ‘Her Majesty’, ‘Polythene Pam’/’She Came In Through The Bathroom Window’, ’Golden Slumbers’/ ’Carry That Weight’, ’The End’) ......

Track Download ERROR. Information below.

System.IO.PathTooLongException: Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.
   в System.IO.PathHelper.GetFullPathName()
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   в System.IO.File.Create(String path)
   в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__91.MoveNext()

**Comment by ImAiiR** [comment]
Should be fixed in the latest version.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.16

**Comment by fominator** [comment]
ok! Thank you
