### ISSUE TITLE
Problems in the file cover jpg in file music

### ISSUE THREAD

**Issue by Superhackman** [ImAiiR/QobuzDownloaderX#32]
The 1400x1400 jpg cover is not embedded in the music file, the embedded cover is 600x600
![image](https://user-images.githubusercontent.com/27593140/84920254-887aa000-b088-11ea-9c64-1a305714d443.png)
![image](https://user-images.githubusercontent.com/27593140/84920428-c081e300-b088-11ea-9097-3ae4da9326af.png)

**Comment by ImAiiR** [comment]
Open the tags panel in QBDLX, look for "Embedded Art Size", and if you want the highest quality file (the one that gets saved as the `Cover` file) embedded, set the option to `max`.

**Comment by Superhackman** [comment]
@ImAiiR I'm sorry I already found out about this, I found out before you answered and closed this
