### ISSUE TITLE
Downloading Songs Makes The Network Clogged

### ISSUE THREAD

**Issue by technoize** [ImAiiR/QobuzDownloaderX#34]
Hi, when downloading using the QDLX other devices using the same WiFi network became weak and sometimes being disconnected. Is this normal? It's like QDLX is absorbing all the traffic data of the network which does not happen on Tidal DL.

**Comment by ImAiiR** [comment]
I haven't run into this issue myself, but it could very well be my shitty code for downloading. I'm not sure exactly what I could do to try and fix this, as I would need to experience it to try and debug it. I'll keep an eye on it either way, and try to figure out a way to stop this from happening.

If anyone else has run into this, and thinks they have an idea of the cause, please let me know.
