### ISSUE TITLE
Community Channel & Group Chat

### ISSUE THREAD

**Issue by RafahEnzong** [ImAiiR/QobuzDownloaderX#35]
Good day Sir @ImAiiR! I would like to suggest if it's okay with you to have our own community on telegram by having a group chat, this could really help especially discussions regarding with this tool, and also a channel where we can easily Download new releases.

Thanks for all the effort you've done for this tool. This is a really big help for us.

**Comment by ImAiiR** [comment]
I like the idea, but I won't be able to do it myself. I have multiple communities I moderate over already, I have other projects I'm working on, along with just being super busy IRL.

But, with that said, if someone else decides to make a group chat for the tool themselves, they can drop the link and people can join in. I'll join too and drop by every so often to see how everything is going, and try to help those who are having issues. Let me know if that happens!

I'm going to go ahead and close this issue as it isn't really related to the program by itself.

**Comment by RafahEnzong** [comment]
@ImAiiRf If you want with right permission, I'll just make the Group Chat by myself, I'll give you the link, so you can post it in here. I'll just wait for your response. Thanks.

**Comment by RafahEnzong** [comment]
@ImAiiR If you want with your permission, I'll just make the Group Chat myself, I'll give you the link, so you can post it in here. I'll just wait for your response. Thanks.

**Comment by ImAiiR** [comment]
I'm fine with that, go ahead and make the group chat 👍

**Comment by RafahEnzong** [comment]
Great, Thanks @ImAiiR!
If you have time, Here's my Telegram
https://t.me/enzhong
Message me so that I can add you as admin to the GC and talk about few details.

**Comment by ImAiiR** [comment]
Link sends me to "Sorry, this user doesn't seem to exist"

**Comment by RafahEnzong** [comment]
Sorry, this one. t.me/ruffeenzoh

**Comment by RafahEnzong** [comment]
Sorry, this one. https://t.me/ruffeenzoh
