### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NicolasZiegler** [ImAiiR/QobuzDownloaderX#37]
Hello, 

today I encounter this problem:

Failed to get streaming URL. Error information below.

System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.QobuzDownloaderX.createURL(Object sender, EventArgs e)Downloading - 04 - 4. Sarabande ......Track Download Done!
Downloading - 05 - 5. Menuet I ......Track Download Done!
Downloading - 06 - 6. Menuet II ......Track Download Done!
Failed to download (First Phase). Error information below.

System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__99.MoveNext()

I would be very grateful if you can fix it. Thanks in advance

**Comment by ImAiiR** [comment]
Looking into fixing this ASAP, need to find the cause of it first. From testing it's possible that this is an error on the side of Qobuz. It does seem like just retrying downloads is a workaround, the program will skip existing files and try to download the failed file again.

If anyone finds the source of the issue, let me know and I'll work on implementing a fix.

**Comment by NicolasZiegler** [comment]
Thanks for your quick response. I also have found the cause of the error. It is because of the temporary shutdown of qobuz server. Now it is working again

**Comment by ImAiiR** [comment]
Awesome, so nothing caused by the program, sounds good. If it starts acting up again let me know!
