### ISSUE TITLE
New "Bad Gateway" error

### ISSUE THREAD

**Issue by ChuckWheat** [ImAiiR/QobuzDownloaderX#38]
Just today, the software will successfully download a few tracks of an album before reporting this error:

 Failed to download (First Phase). Error information below.

 System.Net.WebException:` The remote server returned an error: (502) Bad Gateway.

   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__99.MoveNext()

I'm not sure if it is related to the recent Qobuz desktop application update that also occurred today.

I will continue to try different things and see if the behavior changes.

Thank you for your work on this software.

**Comment by ImAiiR** [comment]
Looking into fixing this ASAP, need to find the cause of it first. From testing it's possible that this is an error on the side of Qobuz. It does seem like just retrying downloads is a workaround, the program will skip existing files and try to download the failed file again.

If anyone finds the source of the issue, let me know and I'll work on implementing a fix.

**Comment by ImAiiR** [comment]
https://github.com/ImAiiR/QobuzDownloaderX/issues/37#issuecomment-652689480
