### ISSUE TITLE
Catch NullReferenceException for ALL possibly null JToken

### ISSUE THREAD

**Issue by tomty89** [ImAiiR/QobuzDownloaderX#41]
When getting metadata from `joTrackResponse`, all fields that get values from a token that are two or more level down should check whether it is referencing a null.

For example:
```
meh = (string)joTrackResponse["a"]
```
is probably fine without a null check / try-catch as it only set meh to a null string.
but
```
meh = (string)joTrackResponse["b"]["c"]
```
is not because `joTrackResponse["b"]` could be null and we are referencing it (instead of turning it into a e.g. string).

I'm not sure about the "nullability" of `int` so for fields of that type might need further fix (e.g. set to 0 when the token is null?).

Btw there's also the typo `performerName = DecodeEncodedNonAsciiCharacters(albumArtist)`.

**Comment by ImAiiR** [comment]
Fixed the typo.
Went ahead and added a try-catch to the main culprit of issues, which was `performerName`, so that should be good to go.
I'll implement fixes for others that cause issues as they are reported.
