### ISSUE TITLE
24bit-96kHz can't working

### ISSUE THREAD

**Issue by sureshraj1** [ImAiiR/QobuzDownloaderX#44]
hi hello friend's i well try to Download 24bit-96kHz but downloading  for 16bit Onliy can you check Please ...
original file song:https://www.qobuz.com/it-it/album/chellamma-from-doctor-anirudh-ravichander/tyxgrtehu45fa
Ex:https://lookimg.com/images/2020/07/20/PkQLTU.png

**Comment by ImAiiR** [comment]
Tested on my end and it downloaded fine in 24/96, so my guess is the account you're using isn't able to stream in that quality. Going to this link for the release, check and see if you're able to stream it in the highest quality. https://play.qobuz.com/album/tyxgrtehu45fa

You can check by selecting the quality through the player.
![image](https://user-images.githubusercontent.com/22158489/87988246-037f0e00-caae-11ea-9a0b-1bae00b693f4.png)

If the web-player is able to play it in 24/96, then double check to make sure that you're 1, using the same account, and 2, that the quality selector in QBDLX is set to the highest quality.
