### ISSUE TITLE
Won't download some albums.

### ISSUE THREAD

**Issue by rodneymw** [ImAiiR/QobuzDownloaderX#46]
Starting Downloads...

Failed to download (First Phase). Error information below.

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__250.MoveNext()

**Comment by rodneymw** [comment]
The same albums will download using Qo-DL-Reborn.

**Comment by ImAiiR** [comment]
Have a link to an album that gives this error?

**Comment by rodneymw** [comment]
http://open.qobuz.com/album/tgcpelsvrbg7a

**Comment by ImAiiR** [comment]
I believe this is caused by an issue I just recently fixed, but haven't pushed a full release for yet. It's due to the older regex matching an ID that it shouldn't, which will cause an error. I've updated the regex and will push a new release later today.

**Comment by rodneymw** [comment]
Okay, thank you!

**Comment by ImAiiR** [comment]
Sorry for the delay, should work downloading from the latest version. Open a new issue if you run into any new problems. 👍
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.19

**Comment by rodneymw** [comment]
Thank you for quickly resolving the issue! You're the best!
