### ISSUE TITLE
Truncated Track Names

### ISSUE THREAD

**Issue by arelas** [ImAiiR/QobuzDownloaderX#48]
Not sure if this has been addressed and I missed it, but I have an issue where long track names get truncated.  Is this something that could be fixed?

Example:
06 Ready to Go (Get Me Out of M.flac

Should be:
06 Ready to Go (Get Me Out of My Mind).flac

**Comment by ImAiiR** [comment]
This is done to avoid errors with filenames becoming too long, which happened a lot in previous versions, which caused downloads & tagging to fail. Maybe in the future I can add something to increase the limit on the user's end.

Also love that song.

**Comment by ImAiiR** [comment]
Added the feature I mentioned in the latest version - https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.21
