### ISSUE TITLE
FLAC stream not found at starting position.

### ISSUE THREAD

**Issue by X-OBJECT** [ImAiiR/QobuzDownloaderX#49]
error inquate today:
![bug](https://user-images.githubusercontent.com/54378161/89446284-ff651880-d75c-11ea-9637-abec1ae99b95.jpg)

Starting Downloads...

Downloading - 01 - Exodexo ......

Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
   в TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   в TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__250.MoveNext()

**Comment by ImAiiR** [comment]
This is usually caused by trying to download a FLAC stream without an active subscription that'll allow it. Double check and make sure the account's subscription is still active.

**Comment by X-OBJECT** [comment]
> This is usually caused by trying to download a FLAC stream without an active subscription that'll allow it. Double check and make sure the account's subscription is still active.

checked. yes. subs out. replace subsribed. tnx
