### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by mallikh67** [ImAiiR/QobuzDownloaderX#51]
System.NullReferenceException: Object reference not set to an instance of an object.
at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

same error. my new user name and pwd are working when streaming in qobuzz app. but downloads from qbdlx not working.solve this issue

**Comment by ImAiiR** [comment]
Made a new account to test logging in, sure enough same error, working on a fix. For now, using the alternate method for logging in still seems to work, so you can use that for now while I fix this. - https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)

**Comment by ImAiiR** [comment]
Alright, quicker fix than expected, fixed in the latest version - https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.20

**Comment by mallikh67** [comment]
thanks. new version working
