### ISSUE TITLE
Download does not start

### ISSUE THREAD

**Issue by clash108** [ImAiiR/QobuzDownloaderX#53]
![769e531071](https://user-images.githubusercontent.com/56191610/89895721-4056a480-dc17-11ea-96f5-0a718307aac9.jpg)
Using the last folder you've selected as your selected path!
Folder selected but download does not start Windowns 7
this version worked well, but recently this version 0.9.9.15 stopped working
Is it possible to somehow solve the problem? thank you!

**Comment by ImAiiR** [comment]
This is usually a problem with the taglib-sharp.dll file. If you still have an older installation of QBDLX, you can just take the taglib-sharp.dll from that and replace the one in the latest version, and that should fix the problem. That or reinstalling it completely. Let me know if that fixes the issue.

**Comment by clash108** [comment]
@ImAiiR this also did not help me, I put the old file taglib-sharp.dll file. in the new version
maybe there is another solution? thank you!

**Comment by ImAiiR** [comment]
I'm not sure what else could've caused this issue. Has this only started happening after updating to 0.9.9.20?

**Comment by clash108** [comment]
@ImAiiR no it started to happen 0.9.9.16

**Comment by ImAiiR** [comment]
Weird, there wasn't really any major changes in that version. I guess we can just try a few things.

- Run QBDLX as administrator.
- Delete and completely reinstall latest version into a new directory so there should be no saved settings.
- Not sure if this would be anything, but maybe restart computer and try the steps above again.

Wish I could help here more, but I have no idea what in the world is causing this issue.

**Comment by clash108** [comment]
@ImAiiR damm i did it but didn’t help, it also doesn’t start loading

**Comment by clash108** [comment]
@ImAiiR maybe there are some other ideas to make this work? bro

**Comment by ImAiiR** [comment]
I wish I had more ideas about what it could be, but I can't think of anything that would be the cause, other than what I had already mentioned. The only time I've seen this issue was what I mentioned before about the taglib dll file. I'm going to keep my eye on other causes, but at the moment I'm unable to help, sorry.

**Comment by clash108** [comment]
@ImAiiR 
Is it possible to fix this error in this particular version? 0.9.9.15.

Failed to download (First Phase). Error information below.
System.Net.WebException

**Comment by ImAiiR** [comment]
You would need to send the latest log from the QBDLX exe path for me to figure out that error, but to fix issues in that version, you would need to download the source code and implement fixes from later versions to get it working correctly again.

**Comment by clash108** [comment]
@ImAiiR 
the problem was solved with the update SP1
