### ISSUE TITLE
Option to add - right after track number

### ISSUE THREAD

**Issue by apathy** [ImAiiR/QobuzDownloaderX#57]
Hey, really great tool but would appreciate having the option to add a "-" right after a track number. For example, current files look like: 02 Song Name.flac while 02 - Song Name.flac looks cleaner.

**Comment by apathy** [comment]
Ended up doing it myself for now, thanks again for the tool.

**Comment by ImAiiR** [comment]
Added in the latest version, it's an option in the tag options section.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.22
