### ISSUE TITLE
Full screen and gui

### ISSUE THREAD

**Issue by EddyCarlos** [ImAiiR/QobuzDownloaderX#58]
Can add a button for minimize and maximize, and edit the size of the software? I had to hide my taskbar just to uncheck some tags as seen from the pictures below. Thank You!

![Screenshot (376)](https://user-images.githubusercontent.com/18585562/90961725-792b2f00-e4dd-11ea-89d6-6d72fa761421.png)
![Screenshot (377)](https://user-images.githubusercontent.com/18585562/90961727-7b8d8900-e4dd-11ea-9a5d-b29cff4a2a5b.png)

**Comment by ImAiiR** [comment]
Not full screen or window resizing, but I did re-organize the tag options in the latest version, so it should (hopefully) fit to your screen now. Let me know if it doesn't. - https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.22

**Comment by EddyCarlos** [comment]
It looks great now. Thank you!

![Screenshot (378)](https://user-images.githubusercontent.com/18585562/91276116-a87abe00-e7b3-11ea-8525-4d857f5ed779.png)
