### ISSUE TITLE
Downloaded labels

### ISSUE THREAD

**Issue by LETRA** [ImAiiR/QobuzDownloaderX#6]
Hi. I'm interested in finding a replacement for Qo-DL Reborn. I downloaded your app but can't find the option to download labels. Is this possible or planned? Thank you.

**Comment by ImAiiR** [comment]
I've seen some talk about downloading labels, so I'll begin working on that when I can. Not sure which will come first though, between playlists and labels.

**Comment by LETRA** [comment]
Thank you for your answer. I think playlists are already solved by other apps like the one Deezer uses. But the labels can only be downloaded from Qobuz, there is no other option. Anyway, thanks.

**Comment by ImAiiR** [comment]
Added to version 0.9.9.9!
Seemed a bit too easy, so I'm sure there's bugs that need to be fixed. If there are any you find, feel free to create a new issue.
