### ISSUE TITLE
Add option for FLAC 24/44.1

### ISSUE THREAD

**Issue by EddyCarlos** [ImAiiR/QobuzDownloaderX#60]
Downloading 24/44.1 thru the Open Search is ok, but it'd be also nice if there's a FLAC 24/44.1 option added so that you can just paste the link and download 24/44.1 right away without searching it on Open Search

**Comment by ImAiiR** [comment]
I've done some testing with format IDs, and I don't believe Qobuz has one for downloading 24/44.1 specifically, so this isn't something I can add. The quality options on QBDLX are based off of the streaming options from the Qobuz web player.

Here's what I tested, if you're interested.
```
1-4 		= nothing
5 		= MP3 320
6 		= FLAC 16/44.1
7		= FLAC 24/96 (or highest quality possible)
8-18		= nothing
19-26		= MP3 320 (30 Sec Preview)
27		= FLAC 24/192 (or highest quality possible)
28-30		= nothing
31-100		= MP3 320 (30 Sec Preview)
```

I'm fairly sure everything over 100 is just the 30 second preview.
