### ISSUE TITLE
Creation of the folder format (*bit-*kHz) in the first level.

### ISSUE THREAD

**Issue by balleno75** [ImAiiR/QobuzDownloaderX#62]
Creation of the folder format (*bit-*kHz) in the first level.

Hello, is it possible to create the format folder, in the first level of folders???. Example,

Instead of,

..\Jean Michel Jarre\Equinoxe Infinity\FLAC (24bit-48kHz)

Create the folder on the first level,

..\FLAC (24bit-48kHz)\Jean Michel Jarre\Equinoxe Infinity

In this way, we can more quickly locate all the music downloaded in one format or another.

Thank you. A greeting.

**Comment by clash108** [comment]
my suggestion to make 
Jean Michel Jarre - Equinoxe Infinity (2020) (24bit-48kHz) - Hi-Res

**Comment by balleno75** [comment]
To me particularly, I would like it to be created in the following way,

..\FLAC (24bit-48kHz)\Jean Michel Jarre\Equinoxe Infinity

Thus, have the music classified by the type of format and artist.

Thanks.

**Comment by Wim1975** [comment]
or
..\Jean Michel Jarre\FLAC (24bit-48kHz)\Equinoxe Infinity

**Comment by rodfeli** [comment]
> my suggestion to make Jean Michel Jarre - Equinoxe Infinity (2020) (24bit-48kHz) - Hi-Res

+1

Please & thank you!
