### ISSUE TITLE
>16bit/44.1 dl disabled Update API?

### ISSUE THREAD

**Issue by ElegantPercentage** [ImAiiR/QobuzDownloaderX#64]
Unable to dl anything higher 16bit/44.1khz. With sublime+ subscription. Any help would be appreciated.

**Comment by ImAiiR** [comment]
What errors are you getting?

**Comment by ElegantPercentage** [comment]
Not getting any errors. It's just not letting me download higher than 16/44.1.

**Comment by ImAiiR** [comment]
Got a link to the release you're trying to download?

**Comment by ElegantPercentage** [comment]
[https://play.qobuz.com/album/pg2psgw25ovhc](url) [24bit/44.1kHz]

[https://play.qobuz.com/album/wrm7ywlsmfjga](url)  [24bit/88.2kHz]

Those two are only giving me 16/44.1

When I dl them. The folders are mislabeled I might add. They're saved in the directory of chosen quality. Ex. 24/44.1 or 24/88.2 But files are 16/44.1.

**Comment by ImAiiR** [comment]
Alright, just tested them on my end, and the files came out fine. So this is most likely on your end, unless an update is rolling out slowly to others that is breaking the program.

First, can you open the debug settings on the program, and tell me what the "Format ID" is set to when trying to download?
(Open the debug settings by slowly clicking the qbdlx log at the top until they appear)

**Comment by ElegantPercentage** [comment]
Not sure what to click to get into the debug settings qbdlx. But I've had it set to FLAC 24/96 & FLC 24/192 in the app.

**Comment by ImAiiR** [comment]
Sorry, I meant to click the qbdlx logo, not log. At the top right of the program. Just keep clicking it slowly until the settings appear.
If the format id is displaying the correct number, then it's most likely an issue with the account. If you can, test streaming through the web app, and see if it will allow you to stream in the highest quality.

**Comment by ElegantPercentage** [comment]
Format ID 27 (24/192), & 7 (24/96). I ended up using the native app. And was only getting 16/44.1 Red Book quality. This is a HiFi sublime account. Seems to be an issue with the account.
