### ISSUE TITLE
No "date" tag in downloaded file

### ISSUE THREAD

**Issue by ShaggyRogers89** [ImAiiR/QobuzDownloaderX#65]
There is no date tag in downloaded file, even it set on in chosen tags

**Comment by ImAiiR** [comment]
Happening with all releases? If not, which releases are causing this to happen?

**Comment by ShaggyRogers89** [comment]
All of releases that i downloaded.
[image: 2020-09-13 (4).png]
---------- Forwarded message ---------
От: AiiR <notifications@github.com>
Date: вс, 13 сент. 2020 г. в 07:41
Subject: Re: [ImAiiR/QobuzDownloaderX] No "date" tag in downloaded file
(#65)
To: ImAiiR/QobuzDownloaderX <QobuzDownloaderX@noreply.github.com>
Cc: ShaggyRogers89 <duningrunge89@gmail.com>, Author <
author@noreply.github.com>


Happening with all releases? If not, which releases are causing this to
happen?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ImAiiR/QobuzDownloaderX/issues/65#issuecomment-691611377>,
or unsubscribe

**Comment by Beaker66** [comment]
I can confirm this..
It all releases

**Comment by Beaker66** [comment]
Actually. if you download in mp3. The date tag does appear, it just seems to be happening when downloading on FLAC

**Comment by notmaroun** [comment]
I can confirm that this is still an issue. I'm downloading FLACs and I don't see a date in my files. I wonder why it's only for FLACs.

**Comment by notmaroun** [comment]
Hello I've figured out what it is! The date is there, it's just formatted incorrectly... Dbpoweramp sees it as YYYY/DD/MM, but I have to correct it to DD/MM/YYYY for Musicbee to read it.

**Comment by DrGogu** [comment]
Date not seen on VLC Android for FLAC files.
