### ISSUE TITLE
Starting Downloads

### ISSUE THREAD

**Issue by tt0331** [ImAiiR/QobuzDownloaderX#71]
Starting Downloads...

Downloading - 01 - Licht überm See (Live) ......

Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
   在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   在 TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   在 QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

**Comment by vad62** [comment]
Same error, does not load tracks.

**Comment by Ammigo1** [comment]
I have had the same problem since about 12/21/2020. **No items can be downloaded at all**. Please, is there a solution? Thank you
![Screenshot](https://user-images.githubusercontent.com/76650087/103170773-44dacd00-4847-11eb-9116-10e922311225.jpg)

**Comment by Vilagamer999** [comment]
It means your account is not premium, free users can't download tracks.
