### ISSUE TITLE
Download Error !

### ISSUE THREAD

**Issue by vad62** [ImAiiR/QobuzDownloaderX#72]
Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
在 TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
在 QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

**Comment by vad62** [comment]
Track Download ERROR. Information below.

System.InvalidOperationException: Указан недопустимый URI запроса. URI запроса должен быть абсолютным URI, или необходимо задать BaseAddress.
   в System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   в System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   в System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   в System.Net.Http.HttpClient.GetAsync(String requestUri, HttpCompletionOption completionOption)
   в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

**Comment by Ammigo1** [comment]
I have had the same problem since about 12/21/2020. **No items can be downloaded at all**. Please, is there a solution? Thank you
![Screenshot](https://user-images.githubusercontent.com/76650087/103170738-faf1e700-4846-11eb-94be-0b12c5e9eccb.jpg)

**Comment by ImAiiR** [comment]
> Track Download ERROR. Information below.
> 
> System.InvalidOperationException: Указан недопустимый URI запроса. URI запроса должен быть абсолютным URI, или необходимо задать BaseAddress.
> в System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
> в System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> в System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> в System.Net.Http.HttpClient.GetAsync(String requestUri, HttpCompletionOption completionOption)
> в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

I've been away for awhile, but is the issue still happening? If so, can you provide a link to the release that's causing the issue?

**Comment by Ammigo1** [comment]
No links are working. Any selected ones do not work.
For example, these
https://open.qobuz.com/album/m4lysr6oswgnb
https://open.qobuz.com/album/d7rchuzba48lc
https://open.qobuz.com/album/h131bre6yzqeb
https://open.qobuz.com/album/0060253753028
I am using version 0.9.9.22

**Comment by ImAiiR** [comment]
@Ammigo1 Check what I've posted on the issue you've opened, I'll try to help you over there.

**Comment by EstebanOD** [comment]
I have the same issue; how do we resolve it ?

> Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
   à TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   à TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   à QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

**Comment by Vilagamer999** [comment]
It means your account is not premium, free users can't download tracks.
