### ISSUE TITLE
Sorry for the dumb question, but is there an easy install guide for this program? I'd be happy to buy the creator a coffee is a step by step guide was posted :-)

### ISSUE THREAD

**Issue by GorillaCentral** [ImAiiR/QobuzDownloaderX#73]
Anyone?

**Comment by RolandWH** [comment]
1. Download the .zip file from GitHub in the release section of the repository.

2. Unzip the .zip file wherever you like as long as you remember it.

3. Go to wherever you unzipped the files and double click on the QobuzDownloaderX.exe file.

4. Enter your Qobuz username and password and the click login.

5. After you are logged in click the "Choose folder" button and navigate to wherever you would like to save your music (does not need to be the same as where you unzipped the application).

6. Click the "Open Search" button and type in the name of your song/album then press enter.

7. Once you find the right album/song copy the url (this is the bit of text that starts with https:// ).

8. Close the search window and paste the url into the text box to the left of the download button.

9. Click download!

10. Click "Open folder" and a window should pop up with your downloaded music


Repeat steps 3-10 except for number 5. Next time you run the application it should remember your login details so you only need to click login.

Hope that helps 😊

**Comment by Emanef** [comment]
I'm struggling with this too. There is no .exe file in the zip. I can import it into my Github desktop but no idea how to get it working from there. Any ideas?!
