### ISSUE TITLE
No items can be downloaded at all. Please, is there a solution?

### ISSUE THREAD

**Issue by Ammigo1** [ImAiiR/QobuzDownloaderX#74]
No items can be downloaded at all. Please, is there a solution? I have noticed the problem since about 12/21/2020. Thank you.
![Screenshot](https://user-images.githubusercontent.com/76650087/103170803-7c497980-4847-11eb-97ba-ece86031d22c.jpg)

**Comment by ImAiiR** [comment]
Just tested this on my end, and it seems to work fine, same link. Double check to make sure your subscription is still active by trying to stream the album through the Qobuz web player.

**Comment by Ammigo1** [comment]
Thank you, I made it. The links seem to work to download and play only in mp3 320 quality. The problem seems to be with the subscription. But I don't understand why. Could it have been blocked due to excessive downloads? In any case, thank you for your willingness.

**Comment by ImAiiR** [comment]
If the subscription expires, then the downloads from QBDLX will be the 30 second MP3 320 preview no matter what. Same thing happens if you try to stream from the web player with an inactive subscription. Only way to download properly again is to get an active subscription again.
