### ISSUE TITLE
Fake FLAC and tag errors (MP3.flac)

### ISSUE THREAD

**Issue by EstebanOD** [ImAiiR/QobuzDownloaderX#77]
EDIT: I think I might've figured the main issue!!!
When I download a 16bit FLAC (for example), it'll download an MP3 file and just change the .mp3 to .flac; but inside it'll still be MP3 (Spek clearly says it, and foobar doesn't even want to play it).
Because even tho I asked for a FLAC, it downloads an MP3.
So basically it's an MP3 hidden in a FLAC, hence why the tags don't work.

Since it seems like the other guy that had the same issue isn't responding I'll open a new one

Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
à TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
à TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
à QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

I tried to download https://play.qobuz.com/album/a9ju02ugh0i2a
It downloads the 1st music file and the cover, but then the tags bug, and everything stops.

Edit: the tags works and nothing stops when I download in mp3, it only bugs for FLAC

**Comment by ImAiiR** [comment]
I can't seem to test this on my end as the URL leads to a 404 for me. Probably because of a country restriction. Do you have any other releases that do this?

**Comment by EstebanOD** [comment]
> I can't seem to test this on my end as the URL leads to a 404 for me. Probably because of a country restriction. Do you have any other releases that do this?

I think it does that with all albums
https://play.qobuz.com/album/yhtos71d25dnb (It's a 24/96 from Japan but I don't think there's a country restriction on it)
https://play.qobuz.com/album/g3vkk4zjp404a (a 24/88.2 from the US, it's Travis Scott, no country restriction here either)

**Comment by ImAiiR** [comment]
Can you confirm that your subscription is still active by using the web player, and seeing if you can play the full song(s)? This issue is usually because you don't have an active subscription. Tested the top link and that one downloaded fine, so I believe it's most likely an account issue.

**Comment by EstebanOD** [comment]
I used a different account and it seems the issue is indeed resolved
