### ISSUE TITLE
error to download please help me

### ISSUE THREAD

**Issue by kogumero0** [ImAiiR/QobuzDownloaderX#79]
TagLib.CorruptFileException: FLAC stream not found at starting position.
在 TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
在 TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
在 QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

how can i solve it?

**Comment by Vilagamer999** [comment]
It means your account is not premium, free users can't download tracks.
