### ISSUE TITLE
Failed to download.

### ISSUE THREAD

**Issue by rodneymw** [ImAiiR/QobuzDownloaderX#8]
Failed to download (First Phase). Error information below.

System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at QobuzDownloaderX.QobuzDownloaderX.DateConvertion(String Input)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__75.MoveNext()

**Comment by ImAiiR** [comment]
Which version of QBDLX are you using?

**Comment by rodneymw** [comment]
Version 0.9.9.10. Okay, I'll have to try that. I was wondering, would it be possible to add the ability to download my favourite albums? Thanks

**Comment by ImAiiR** [comment]
I can look into that. Open a new issue for that and I'll mark it as a feature request. For now, could you send a link to the album that was giving you the error? I can look into it and try to find the cause of the error.

**Comment by rodneymw** [comment]
https://play.qobuz.com/album/hpt5h167aoyxc

Thank You!

**Comment by ImAiiR** [comment]
Weird. Using the release version 0.9.9.10, it's downloaded fine for me, release date included and everything. Could you send a screenshot of the program when it gives you the error? (Have tags panel open too please)

![image](https://user-images.githubusercontent.com/22158489/77474209-18dc7800-6ded-11ea-8e83-b7f89fcb460f.png)

![image](https://user-images.githubusercontent.com/22158489/77474244-2e51a200-6ded-11ea-83f4-798dddf07576.png)

**Comment by rodneymw** [comment]
On my account it is available in High Resolution. It also won't download when unchecking the release date.
![Annotation 2020-03-24 153943](https://user-images.githubusercontent.com/43912455/77474912-ef6c1e00-6de5-11ea-8782-796439662f75.png)

**Comment by ImAiiR** [comment]
It's available in Hi-Res for me too, I just download FLAC 16bit along with MP3 and FLAC 24bit to test all of them.
What country is the account located in? I can make a new account and test it in that region.

**Comment by rodneymw** [comment]
The account is located in the US. I just tried downloading a different album and I had the same results.

**Comment by ImAiiR** [comment]
Are you located in the US too? If not, where are you using this from (VPN or not)? It could be an issue with region when grabbing the response from the API.

**Comment by rodneymw** [comment]
Yes, and I wasn't using a VPN. I tried connecting to a server in France and had the same issue.

**Comment by rodneymw** [comment]
Okay, I solved the issue. It was caused by my date/time settings being set to English UK. Unfortunately I'll have to change it back to the US setting to download using the app. Thanks for the help!

**Comment by ImAiiR** [comment]
That's unusual. It's probably due to the API showing an epoch timestamp, so I'm converting it using DeltaTime within the program to get a readable release date. Conversion was probably broken by the time being something unexpected. That's my _uneducated_ guess, lol.

Let me know if you run into any other issues.
