### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by NicolasZiegler** [ImAiiR/QobuzDownloaderX#80]
Hi,

I have encountered this bug. The problem is from last month, I have troubled with log in my account to qobuzDownloaderX. When I logged in with normal Username and password, it did not work. I changed to log in with id & token, and it worked till yesterday. Today, both login method doesn't work anymore. I still can log in to the qobuz webplayer to hear music without any problem.

Here is the error log
System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at QobuzDownloaderX.LoginFrm.getSecretBG_DoWork(Object sender, DoWorkEventArgs e)

I hope you can fix it. Thanks in advance

**Comment by cesarleeds** [comment]
Yes, same issue here.

With both login methods, email+pwd, id+token, both provide the same error log.

**Comment by snakeandarrow** [comment]
I tried both methods as well, no luck

**Comment by Wim1975** [comment]
Yes, same problem here.

**Comment by jraiver** [comment]
I fixed it. Added pull request

**Comment by jraiver** [comment]
The developer may not see the request. Check out the compiled version.

**Comment by snakeandarrow** [comment]
That's great.  Thanks.  How do I launch the program with the revised code?  I have the prior version as an exe file.

**Comment by jraiver** [comment]
> That's great. Thanks. How do I launch the program with the revised code? I have the prior version as an exe file.

write me a telegram. @hiddenUserEurope

**Comment by ImAiiR** [comment]
Added a release with the fix from @jraiver (thanks!)
Sorry for the delay!
