### ISSUE TITLE
Track Download ERROR

### ISSUE THREAD

**Issue by sangtp11296** [ImAiiR/QobuzDownloaderX#84]
Hello, thanks for your dedication to this project.
I used the older version of the app, works perfectly. But I have an issue with the newest version.

Track Download ERROR. Information below.

TagLib.CorruptFileException: FLAC stream not found at starting position.
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__263.MoveNext()

I re-logined many times but still not working.

**Comment by ImAiiR** [comment]
This usually means the account your using isn’t paid for. You can check this on the official web player. If you’re not able to play tracks there, downloads won’t work.

**Comment by sangtp11296** [comment]
Yes, you're right, there are some problems with my account. Thanks.

**Comment by jclackers** [comment]
Hello friends, someone, have accont for QOBUZ download please
