### ISSUE TITLE
Could not login i got this error log

### ISSUE THREAD

**Issue by lilstavo** [ImAiiR/QobuzDownloaderX#85]
[Latest_Error.log](https://github.com/ImAiiR/QobuzDownloaderX/files/6328458/Latest_Error.log)

**Comment by plamberti** [comment]
Suddendly, this evening I got a similar error message trying login

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext() in S:\QobuzDownloaderX-master\QobuzDownloaderX\LoginForm-v2.cs:line 585

I have downloader version 0.9.9.22 patched to v.0.9.9.23 two months ago or something.
Until yesterday things went fine.

Thank you

**Comment by Lostone2** [comment]
> Suddendly, this evening I got a similar error message trying login
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
> at QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext() in S:\QobuzDownloaderX-master\QobuzDownloaderX\LoginForm-v2.cs:line 585
> 
> I have downloader version 0.9.9.22 patched to v.0.9.9.23 two months ago or something.
> Until yesterday things went fine.
> 
> Thank you
 
Have you solve this problem ? Same issue too

**Comment by plamberti** [comment]
I had no time to investigate further, but launching downloader inside VisualStudio, even in release mode, the issue doesn't come out. Launching downloader the usual way (outside VisualStudio), the issue still persists.
It seems a software bug, perhaps from some external library update, non a Qobuz issue.
HTH
