### ISSUE TITLE
Cannot Download music

### ISSUE THREAD

**Issue by BattiScopa** [ImAiiR/QobuzDownloaderX#86]
![image](https://user-images.githubusercontent.com/54958063/115930167-49c42c00-a489-11eb-859b-d5dbc346f681.png)
I am having this problem right here.

**Comment by lowie228** [comment]
I have the same problem.

**Comment by BattiScopa** [comment]
Rip

Il mar 27 apr 2021, 17:12 lowie ***@***.***> ha scritto:

**Comment by nativekative** [comment]
Ya same problem for me ,almost same error.

**Comment by lmchow** [comment]
I sometimes have the same problem, but when I open qobuz while listening to a song, it starts to work again
