### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by mallikh67** [ImAiiR/QobuzDownloaderX#88]
using latest package of qobuz downloader x and having an qobuz paid account but not able to login to downloader app . kindly solve this issue. this is the error log of qobuzdownloader x

System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

**Comment by Lostone2** [comment]
Same issue

**Comment by jumpman95** [comment]
I also can't login, but the issue presents different. Running QBDLX 0.9.9.23, the main screen will say that the id and secret were obtained, and that its logging in, but then it just hangs there until it automatically closes.

**Comment by caxcs** [comment]
I had the exact same problem, did you solve it?
