### ISSUE TITLE
Add option to download favourites.

### ISSUE THREAD

**Issue by rodneymw** [ImAiiR/QobuzDownloaderX#9]
Here would be the link to download one's favourite albums.
https://play.qobuz.com/user/library/favorites/albums

**Comment by ImAiiR** [comment]
Added the ability to download favorite albums in version 0.9.9.11! Favorite tracks & artists will hopefully be worked on and added soon.

https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.11
