### ISSUE TITLE
Stopped downloading Hi-Res files.

### ISSUE THREAD

**Issue by KENESOLJASMUSIC** [ImAiiR/QobuzDownloaderX#95]
The program stopped downloading Hi-Res files, instead it downloads only 16-Bit CD Quality 44.1 kHz - Stereo. Or has something changed in Qobuz.com?

**Comment by KENESOLJASMUSIC** [comment]
Update: Some tracks are being downloaded in Hi-Res.

**Comment by KENESOLJASMUSIC** [comment]
And I'm a little tired, of these mistakes...
![Screenshot 2021-08-09 201651](https://user-images.githubusercontent.com/88329871/128721226-e8c5a08a-e07d-4e5b-9360-59d8016c2127.png)
I hope this can be fixed.

**Comment by nnt1** [comment]
Which link did you used ?

**Comment by KENESOLJASMUSIC** [comment]
> Which link did you used ?

Link with error or with Hi-Res?

**Comment by nnt1** [comment]
> > Which link did you used ?
> 
> Link with error or with Hi-Res?

Both, so I can test on them.

**Comment by KENESOLJASMUSIC** [comment]
> > > Which link did you used ?
> > 
> > 
> > Link with error or with Hi-Res?
> 
> Both, so I can test on them.

A link to an album with an error (although, any album downloads with such an error, I think the problem is in the
"QobuzDownloaderX"): https://play.qobuz.com/album/b3ji11rp7wdta

For example, this album downloads to Hi-Res: https://play.qobuz.com/album/0614427903723

And this one is marked as Hi-Res on the site, but only the CD version is downloaded: https://play.qobuz.com/album/k43q1q3kx88fa
![Screenshot 2021-08-10 210608](https://user-images.githubusercontent.com/88329871/128891664-1e6881e4-769b-44ee-ba04-3c0e4341bf80.png)
![Screenshot 2021-08-10 210440](https://user-images.githubusercontent.com/88329871/128891475-f2d5dd2c-37fc-451d-916c-587a49a905df.png)

**Comment by nnt1** [comment]
https://play.qobuz.com/album/b3ji11rp7wdta
This link I can download successful, your problem may be difference region ? My account in France
![image](https://user-images.githubusercontent.com/44799333/128892967-b0ff753e-53d2-4309-b161-a2d81ec5a29d.png)

No problem with the second link:
![image](https://user-images.githubusercontent.com/44799333/128893401-448d58ac-c089-4a99-b2c1-e696a64fec4a.png)

**Comment by KENESOLJASMUSIC** [comment]
Most likely a problem with the region... It's a pity.

**Comment by KENESOLJASMUSIC** [comment]
But, a year ago, there were no such problems...

**Comment by nnt1** [comment]
I'm not sure about. If you want, you can email for me and I can check with your login to see what happen. My email in my profile.

**Comment by KENESOLJASMUSIC** [comment]
I still do not understand what the problem is, now Hi-Res is being downloaded, perhaps sometimes there are restrictions on the part of the publisher for the regions.
