### ISSUE TITLE
Can't log in anymore version 0.9.9.23

### ISSUE THREAD

**Issue by DruidCtba** [ImAiiR/QobuzDownloaderX#97]
The GUI can no longer log in with my QOBUZ account!

I can download via qobuz-dl via command.com, but no longer via the ImAiiR/QobuzDownloaderX GUI.

What happened? I'm using version 0.9.9.23.

Att.

Druid®.

**Comment by nnt1** [comment]
Note that the email input field is multiple line. Please check to make sure no extra line in that field.
![image](https://user-images.githubusercontent.com/44799333/128958251-030bc2a7-5a0a-44a7-a8dc-753580742bef.png)

**Comment by DruidCtba** [comment]
Here's the error:

System.NullReferenceException: Object reference not set to an instance of an object.
    at QobuzDownloaderX.LoginFrm.<loginBG_DoWork>d__35.MoveNext()

The interesting thing is that it was working, I was testing another login, from a friend, and when I came back with my login, I can't log in anymore.

But the most interesting thing is that if I use the python version installed on command.com, it authenticates, enters and I can download the files, in other words, some problem is occurring in the GUI.

Att.

Druid®.

**Comment by DruidCtba** [comment]
One more question: what are the possible filename templates, is it the same as used for example in MP3TAG?

Att.

Druid®.

**Comment by nnt1** [comment]
As I read the code, filename templates just to define symbol " - " or " " between track number and track name, it's not correct the meaning of "template"
